### ISSUE TITLE
Camera Upload filename

### ISSUE THREAD

**Issue by Nerkill** [haiwen/seafile-iOS#100]
Hi!
Photos and video are loaded with names without a date
For example: IMG_5814.JPG and IMG_5815.MOV

Of these names are not made clear when the photo or video.
Maybe it makes sense to take the name as the file creation date to the file system iOS.
Dropbox upload photos and videos with names like "2015-11-29 13.54.12.jpg"

**Comment by GITchristoph** [comment]
That sounds like a good idea to me as well.

Then on the server the photos can get sorted/tagged/filed automatically based on the date they were taken.

**Comment by poetwang** [comment]
I think keep the image name same as that you export in iPhotos is better. If you want to browser photos based on creation date or other metadata, you can use sofwares such as iphotos, picasa ...

**Comment by Nerkill** [comment]
Maybe then upload the settings to make a choice?
iPhoto or datetime

**Comment by poetwang** [comment]
I do not think this is necessary.
