### ISSUE TITLE
Encrypted Library password

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#101]
Dear Poet

Would it be easy to add the option to automatically reset the passwords for the encrypted Libraries after closing the app or after a specific amount of time?

I would prefer that over the option to manually reset the password every time in the settings.

greetings, Chris

**Comment by poetwang** [comment]
will be added in v2.1.5

**Comment by GITchristoph** [comment]
Cool, thanks!

Kind Regards
