### ISSUE TITLE
Viewing images across different directories crashes app

### ISSUE THREAD

**Issue by tvollstaedt** [haiwen/seafile-iOS#102]
Device: iPhone 6
OS: iOS 9.1
App Version: 2.1.3

If i browse my library and open an image, it will be displayed properly (and i can swipe across other images in that directory). When I hit "back" and open an image within another directory (same library), it still shows the same image i watched before. Swiping to other images mostly causes the app to crash, sometimes it just thinks it is in the old directory and shows those images.

**Comment by poetwang** [comment]
Fixed in 2.1.4.  This version has been submitted to app store and is waiting for review.
