### ISSUE TITLE
App crashes while automatic photo upload

### ISSUE THREAD

**Issue by dbeuchler** [haiwen/seafile-iOS#103]
The app crashes while uploading my Photo Library with more that 2800 photos. Some of the photos will be uploaded but after a while, the app closes.

**Comment by poetwang** [comment]
I will check it soon.

**Comment by dbeuchler** [comment]
Can I help you with some crashlogs or something else?

**Comment by poetwang** [comment]
I will appreciate your help if you can send the crash report which i can use it to find the reason. You can floow http://www.wikihow.com/Send-an-iOS-App-Developer-a-Crash-Report to send the crash report.
Thx

**Comment by dbeuchler** [comment]
I hope this crashlog will help. Please see the attachment
[Crashlog.txt](https://github.com/haiwen/seafile-iOS/files/69960/Crashlog.txt)

**Comment by poetwang** [comment]
thx
