### ISSUE TITLE
Upload not working anymore with version 2.1.5

### ISSUE THREAD

**Issue by BernieO** [haiwen/seafile-iOS#105]
When I try to upload a file with the iOS-app, the app used to ask where I want to save the file. This doesn't work anymore. The iOS-app opens and that's it. Nothing more happening. Seafile-server CE 5.0.2 (for Raspberry Pi on Banana Pi) and iOS-app 2.1.5 on iOS 9.2. Checked with the same configuration on iPad Air (1) and iPhone 4s.

I found an older version (2.1.1) of the iOS app in iTunes on my computer and installed that version on both devices. Upload with this version works as expected.

Please let me know if you need further details or screenshots. I'm happy to provide those if needed.

**Comment by poetwang** [comment]
What is the size and filename of the file? It would be better if you can provide the screenshots.

**Comment by BernieO** [comment]
For the screenshots I created a plain textfile called "textfile.txt" containing the text "This is a very important textfile!". Size is 34 bytes. You can find it here:
http://www.gatsmas.de/seafile/textfile.txt

See sceenshots and a short description of what I did (in version 2.1.1 and version 2.1.5) in the two PDF-files located here (unfortunately uploading to github didn't work):
http://www.gatsmas.de/seafile/expected_behavior_2.1.1.pdf
http://www.gatsmas.de/seafile/wrong_behavior_2.1.5.pdf

**Comment by BernieO** [comment]
I created an account at https://seacloud.cc and checked there as well. Same result on both devices:
- no problems with version 2.1.1
- same problems with version 2.1.5
At least it looks like my server is not misconfigured...

**Comment by poetwang** [comment]
will be fixed in the next version

**Comment by BernieO** [comment]
Great, thank you :-)

**Comment by BernieO** [comment]
I am closing this because this is fixed with new version 2.1.6 of seafile-iOS which was released in the App-store today.
Thanks again!
