### ISSUE TITLE
Internal Seafile link - doesn't open folders

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#106]
Hi poet,

The app currently does not open an internal seafile link to a folder.
There is an error message:
"failed to download file".

Can you reproduce the issue and do you think you can repair this?
Would be great,

Greetings, Chris

**Comment by poetwang** [comment]
I will fix this in the next version.

**Comment by GITchristoph** [comment]
Thanks! ;-)

**Comment by poetwang** [comment]
fixed
