### ISSUE TITLE
Seafile internal link - doesn’t open subfolders

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#108]
Hi!

Thanks for fixing the internal link to folders:
https://github.com/haiwen/seafile-iOS/issues/106

What happens is that seafile always opens only the root folder, not the subfolder. 

All these links open just the Rootfolder:

Link to /Rootfolder/Subfolder1/Subfolder2
Link to /Rootfolder/Subfolder1
Link to /Rootfolder

Hope that makes sense,

Chris

**Comment by poetwang** [comment]
Which device do you use? Do you have multi accounts?

**Comment by GITchristoph** [comment]
This happens on iPhone6 and iPad mini 1. 

I can check iPhone 6s later. 

I only have a single account on each iOS device.

**Comment by poetwang** [comment]
Will be fixed in the next version.

**Comment by GITchristoph** [comment]
Thanks,

Sounds great!

**Comment by GITchristoph** [comment]
thanks for the fix. This is solved ;-)
