### ISSUE TITLE
Moving files to other Libraries don’t work

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#109]
Hi,

I can’t move ot copy files to another Library (encrypted or not encrypted). 

I can move/cooy files within the same Library. 

IPhone 6. All updates on seafile and iOS. 

Greetings, Chris

**Comment by poetwang** [comment]
I tried on my iPhone, it works.
Could you provide more details? copy/move from not encrypted Library  to another not encrypted Library?
Private server or seacloud.cc?

**Comment by GITchristoph** [comment]
Hi poet

I run my own private server. 

Latest version 5. 

It’s a bit funny:

Copying a text file from one unencrypted library to another unencruoted library works. 

Copying 2 pdf or 1 pdf file the same way doesn’t work. 

Copying a text file from an unecrypted library to an encrypted library doesn’t work. 

Does this info help already?


Chris

**Comment by poetwang** [comment]
Seafile can not  copy files between encrypted libraries. So either the src or the dist library is encrypted, it will fail.
Does the name pdf file contains any special characters?

**Comment by GITchristoph** [comment]
The encrypted library part is understood. 

The files that I try to move/copy are named automatically by the scanner.

I think the characters should be alright:
