### ISSUE TITLE
Shibboleth login

### ISSUE THREAD

**Issue by crssi** [haiwen/seafile-iOS#110]
The text filed for entering server on Add account/Shibboleth action is gayedout/disabled on the latest client.
If you try to click around on that very page, the client crashes.

At this point there is no way you can configure to use Seafile with shibboleth on iOS with on the new setup.

**Comment by crssi** [comment]
Today an update is available. Results are the same, the server text field is read-only. :(

**Comment by poetwang** [comment]
fixed in v2.1.8
