### ISSUE TITLE
Editor predictive mode

### ISSUE THREAD

**Issue by vbipr** [haiwen/seafile-iOS#113]
Hi,  
I have problems using the editor. 
 
After typing a few characters predictive mode will suggest some words. Tapping on one of them leaves the curser in the same position, puts a space after the curser, followed by the rest of the suggested word.

E. g. if you type "Sea" "Seafile" is suggested. To select it will result in "Sea| file".

Best  
Adrian

**Comment by poetwang** [comment]
Could you provide more details, which type of file you are editing, markdown or just txt file?

**Comment by vbipr** [comment]
It's the same behavior with both text and markdown files. No matter using English or any other keyboard.

**Comment by poetwang** [comment]
will be fixed in the next version

**Comment by vbipr** [comment]
Thanks. I'm looking forward!

**Comment by poetwang** [comment]
fixed in v2.3.0
