### ISSUE TITLE
Unknown file type when trying to do an upload

### ISSUE THREAD

**Issue by dave-fl** [haiwen/seafile-iOS#121]
I am trying to upload a file that expects a .NZB extension.  For whatever reason I can't select the file from Seafile.  I get a message unknown file type.  Not sure why file type would matter.

**Comment by poetwang** [comment]
How did you upload the file? upload from other apps, or via the icloud?

**Comment by dave-fl** [comment]
Click on choose file button (on page) which launches file dialog box. 

Apps like google drive, owncloud and Dropbox all available. Seafile shows "Does not support file type"

**Comment by dave-fl** [comment]
![img_5237](https://cloud.githubusercontent.com/assets/1098557/14249276/091f81aa-fa47-11e5-81fa-f5d61ba1c089.PNG)

**Comment by GITchristoph** [comment]
Hi

I have the same when I want to up/download a .dwg file to the iOS all Autodesk 360

**Comment by poetwang** [comment]
I will fix it in the next version
