### ISSUE TITLE
iOS 7 issues

### ISSUE THREAD

**Issue by g-mocken** [haiwen/seafile-iOS#122]
Using iOS 7, I observed the following issues (which are not present using iOS 8 or 9):

- swipe any item in the library, then select "more" or "delete" -> nothing happens
- try to upload a photo -> infinitely waiting for upload

I know iOS 7 is fairly outdated. However, some devices cannot be upgraded, and the seafile client app is available for these, but mostly unusable.

**Comment by poetwang** [comment]
Sorry for that, because now it is difficult to maintain the app for iOS7,we have to decide to stop supporting iOS 7.

**Comment by g-mocken** [comment]
I understand that decision, but then I recommend to make available in the AppStore either the latest working version for iOS 7 (provided that it is basically functional and only lacks new features) or none at all (to save users the hassle when trying to get it to work).

**Comment by poetwang** [comment]
I will make the next version only available for iOS8.0+, and keep a latest work version for iOS7.0

**Comment by g-mocken** [comment]
Can you name a release tag which should work for iOS 7.0? Then I can try for myself.

**Comment by poetwang** [comment]
the latest version has already been released. It only supports iOS 8. The previous version is disabled except that v2.1.3 is kept for iOS 7.0. You can try to install v2.1.3.

**Comment by shoeper-seafile** [comment]
Would it be possible to release the iOS 7 version in the app store as a legacy version? Or possibly to tell the app store to deliver that version to iOS 7 users?

**Comment by poetwang** [comment]
The previous version v2.1.3 should work for iOS7

**Comment by shoeper** [comment]
Yes but how can a normal user install it?

**Comment by poetwang** [comment]
The latest versions only support iOS8.0+. In app store under iOS7.0, you can only see the versions which are compatible with that system, which is v2.1.3

**Comment by shoeper** [comment]
Ok, didn't know that. Someone with 7.1 reported it doesn't work or isn't available ...
