### ISSUE TITLE
stopProvidingItemAtURL never invokes 

### ISSUE THREAD

**Issue by iAleks** [haiwen/seafile-iOS#123]
I have found that stopProvidingItemAtURL has not been ever invoked in FileProvider.

**Comment by poetwang** [comment]
The system calls this method as soon as all other processes have stopped accessing the given file. You can override this method to remove the document from the local file system, thus freeing up storage space. You must provide placeholders for any documents you remove.

From https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSFileProviderExtension_Class/
