### ISSUE TITLE
TouchID allows unauthorized access

### ISSUE THREAD

**Issue by amanet2** [haiwen/seafile-iOS#126]
When the touchid authentication fails 3 times there is no fallback authentication - the app just allows you to select an account from the list including the one you failed to authenticate with.  Not sure if this is a true issue or not, but it seems to not match the goals of touchid authentication.

**Comment by poetwang** [comment]
What is the device you use?

**Comment by amanet2** [comment]
I'm using an iPhone 6s running iOS 9.3.2

**Comment by poetwang** [comment]
I can not reproduce it in my device, does it still exists for the latest version? @amanet2
