### ISSUE TITLE
Working with iOS Word (MS)

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#127]
Hi

When i open a file open seafile on iOS, navigate to a docx file and then open it, it will open "read only".
I will then duplicate it and navigate in the iOS app to Seafile and then want to save it back to the same location. It says "file already exists - do you want to overwrite". Yes!

But unfortunatley it only saves a copy on the iPad, it doesn't overwrite directly in the seafile folder.

Is this an expected behaviour or should the docx file usually get saved on the seafile server?
If yes, Is there any way how we can work with word documents directly in the seafile?

iOS client version: 2.4.0

Cheers, Chris

**Comment by freeplant** [comment]
Hi, what app do you use? We will try to reproduce the problem.

**Comment by GITchristoph** [comment]
Hi 

Seafile 2.4.0 and iOS Word


Kind Regards

Chris

**Comment by GITchristoph** [comment]
My first para a bit clearer:


I want to work on docx documents on my seafile with the iOS word app. 
When I open a docx file in Word on iOS then what I do is that I open seafile on iOS, navigate to a docx file and then open it in seafile with “open in” in iOS Word. It will then open "read only" in the word app. 
It will then offer me to dupkicate it, which I will do. To save it I will navigate in the word.app save dialog to Seafile and trying to save it back to the same location in the seafile where I got it from. It says "file already exists - do you want to overwrite". I say yes. but then it will noy save to the seafile. 

That’s it, hopefully clearer. 

Cheers,

Chris
______________

On 01 Jun 2016, at 08:12, Daniel Pan <notifications@github.com> wrote:

Hi, what app do you use? We will try to reproduce the problem.

**Comment by freeplant** [comment]
Yes, I can reproduce the problem. We will fix it soon.

**Comment by GITchristoph** [comment]
Tanks Daniel


Chris
__________

**Comment by poetwang** [comment]
fixed in v2.4.2

**Comment by GITchristoph** [comment]
Just a quick recap for everybody who's working with ios Word and seafile.

**What works:**
- (only when connected to the internet): Open word, navigate to the docx file in seafile, open it, duplicate it, save it back to the same place in Seafile. All changes will be saved to Seafile.
- (with or without internet connection): Use a WebDAV browser (e.g. Documents). Have the docx file that you want to edit downloaded to Documents. Open word, navigate to the docx file in Documents, open it, duplicate it, save it back to the same place in Documents. All changes will be saved to Documents. Later the file can be placed back into seafile, once connected to the internet again.

**What doesn't work:**
- (either offline or online) Open Seafile, navigate to the docx file in seafile, open it in iOS, duplicate it, save it back to the same place in Seafile, make changes, save it. Now the file gets changed somehow (file modify daye changes) but the changes in the word file are not visible.

So it's great now working with iOS Word and Seafile, but only in the ways as described above.

Hope this is of interest.

Cheers, Chris

**Comment by poetwang** [comment]
It should work in the latest version(v2.4.2) using the following two methods.
1. Open seafile on iOS, navigate to a docx file and then open it with “Copy to Word". It will then open "read only" in the word app. Then duplicate it, modify and upload to the same place. 
2. Or you can Open the file from Word.app Open -> More -> Seafile, choose the docx file, modify and save it. The it will be upload to Seafile automatically.
