### ISSUE TITLE
安装ios客户端不能上传手机上的照片

### ISSUE THREAD

**Issue by yonghuming** [haiwen/seafile-iOS#131]
开启了自动上传，
服务器版本：windows seafile 5.1
操作系统：windows 7
防火墙关闭
没有杀毒软件
手机：iPhone 5s
安装之后，手机开启自动上传无法上传照片，Android，ios客户端都不可以不知道是不是windows 7系统的原因还是windows系统权限的 问题，不知道有没有人遇到类似的问题。

**Comment by poetwang** [comment]
请问浏览器可以上传吗？

**Comment by yonghuming** [comment]
浏览器可以上传，现在问题莫名其妙的解决了，我调好了Android客户端之后windows客户端就莫名其妙的好了。真是奇怪的样子啊

**Comment by Andiedie** [comment]
请问是如何解决的呢？
我也是安卓端无法上传，web可以上传。
服务端：RaspberryPi
客户端：Android
