### ISSUE TITLE
PDF files are not shown anymore on IOS10 in the Seafile App

### ISSUE THREAD

**Issue by moetiker** [haiwen/seafile-iOS#132]
Hi,

I've got a serious issue on all of our IDevices. Since the update to IOS10 no PDF's are shown in the client.

When I open any file in the client, even small 1-page-PDFs, the file is downloaded but only a blank page is shown. That happens on IPhone as well as on IPad.

Server 6.0.3

**Comment by GITchristoph** [comment]
+1 

same here.
Server 5.1.4

**Comment by poetwang** [comment]
I will try to fix this problem on IOS10

**Comment by BernieO** [comment]
Same problem here pdfs and also with *.doc and *.pages documents.
Thanks for looking into this!

**Comment by freeplant** [comment]
This issue will be fixed in our next release. We uploaded a fixed version to App Store 2 days ago. The new version should be available to download in this week or next week.

**Comment by moetiker** [comment]
I could update the app today and it works now on ios 10. thanks for the fast fix
