### ISSUE TITLE
No login on iOS 9.3.5 using client 2.4.9

### ISSUE THREAD

**Issue by gn0rr** [haiwen/seafile-iOS#134]
The login process appears to be broken here, and debugging is extremely difficult due to the lack of error messages. Example: I do not get an error message even on a mistyped server name, which cannot be DNS-resolved.

Anyway: When trying to connect to a self-hosted server with a self-signed certificate, I do get the prompt about whether to accept the certificate. But even after clicking YES, nothing more happens, the Login dialog just remains open with a greyed-out login button.

Enabling the Accept-Invalid-Certificates Switch in the Seafile section of iOS settings does not alter this behavior.

Can you please let me know how to proceed? At the very least, more meaningful error adding more messages to the iOS client would be helpful.

**Comment by freeplant** [comment]
We can't reproduce the problem. I suggest you to use LetsEncrypt to bypass the problem.

**Comment by gn0rr** [comment]
On 10/22/2016 03:58 AM, Daniel Pan wrote:
> We can't reproduce the problem. I suggest you to use LetsEncrypt to bypass the
> problem.

Using a properly signed certificate did not help (we tried). However, updating
to the latest version of the app (2.5) did.

Many thanks,
  Andreas
