### ISSUE TITLE
Seafile App "Minimizes"

### ISSUE THREAD

**Issue by wellingtonshane** [haiwen/seafile-iOS#135]
Every time I try to open any files the app closes to the iPhone home screen. The app is still listed in the background but when I go back into it the app acts like I had just started it. To get around this issue I have to open a file that is not currently in the cache and then I can browse freely. I have tried clearing the cache and removing the app but this still happens. Happens on encrypted and non encrypted libraries. iPhone 6 on iOS 9.3.5.

**Comment by wellingtonshane** [comment]
Anyone have any insight on this? I can't use the app at all and have to use the mobile website. I have even tried the seafile server compared to my private server and both have the same issue.

**Comment by freeplant** [comment]
Maybe upgrade to iOS 10 can help.

**Comment by poetwang** [comment]
Can not reproduce it. Could you please share more details or send a video to show how it happens?
