### ISSUE TITLE
Cached photos sometimes fail to save to album

### ISSUE THREAD

**Issue by jr64** [haiwen/seafile-iOS#136]
I have found that sometimes cached photos fail to save to albums correctly.

Steps to reproduce:
- go to settings and clear cache
- go to a folder with a huge amount of pictures (125 in my case)
- Press "Save all photos to album"
- it should work properly the first time, all 125 pictures are saved to Camera Roll
- Press "Save all photos to album" again
- A few pictures randomly fail to save (it only adds around 110)

This also happens if the images are cached for another reason, for instance because of viewing them inside the Seafile app. The bug has nothing to do with saving them twice. It also doesn't happen to the same pictures each time, the ones that fail to save are seemingly random. Additionally, saving them manually works fine.

If that helps troubleshooting, the folder is inside an encrypted library and I have activated "Local decryption" in the settings, though I'm not sure if that is relevant to the issue.

**Comment by poetwang** [comment]
It is a bug and will be fixed in the next version.

**Comment by poetwang** [comment]
fixed in v2.5.1
