### ISSUE TITLE
Perfecting TouchID support: hiding contents and using on every "onfocus"

### ISSUE THREAD

**Issue by stuntsman** [haiwen/seafile-iOS#137]
Compared to Dropbox or Lastpass (and a few other apps) the Seafile client is very forgiving when TouchID is enabled:

- currently TouchID is rarely required in the Seafile app. To make the app feel more secure it should be required everytime the user goes back to the Seafile app (either using app icon or by switching back using the task selector)
- currently the app simply restarts without requiring TouchID even if it was killed by flicking up the app in the task selector
- when TouchID is enabled, the app should entirely hide the app screen contents until the TouchID auth is successful (without this users can easily peek into file previews and file lists). Dropbox hides everything by showing the TouchID fallback number pad that also has the TouchID dialog over: http://www.askdavetaylor.com/wp-content/uploads/2014/10/enable-touchid-dropbox-iphone-7.png
(the app shouldn't expose the account list either until the TouchID auth is successful, as it contains even the server URL and the user name too - that's just too much information to share with anyone)

**Comment by poetwang** [comment]
Now the touchId is configurable for each account. TouchId is used to protect the account that enabled touchID. So I will hide the content in that account and require touchID everytime user goes back to the account. The account list will not be protected by touchID.
