### ISSUE TITLE
SDK integration (via cocoapods) build fails: "ld: library not found for -lssl"

### ISSUE THREAD

**Issue by scottcc** [haiwen/seafile-iOS#139]
I did hit (and apply) the fix for static libraries:

    pre_install do |installer|
        # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
        def installer.verify_no_static_framework_transitive_dependencies; end
    end

However, seems like a library is also needed? Linker error:

    ld: library not found for -lssl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any suggestions?

**Comment by poetwang** [comment]
Add pod 'AFNetworking', '~> 2.6.1' to Podfile

**Comment by scottcc** [comment]
Thanks for your response (sorry for my delay in responding) - but I already have AFNetworking 2.6.3 being used. If it helps, I'm also using swift 3, and the Podfile.lock file section for AFNetworking looks like this:

  - AFNetworking (2.6.3):
    - AFNetworking/NSURLConnection (= 2.6.3)
    - AFNetworking/NSURLSession (= 2.6.3)
    - AFNetworking/Reachability (= 2.6.3)
    - AFNetworking/Security (= 2.6.3)
    - AFNetworking/Serialization (= 2.6.3)
    - AFNetworking/UIKit (= 2.6.3)
  - AFNetworking/NSURLConnection (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.6.3)
  - AFNetworking/Security (2.6.3)
  - AFNetworking/Serialization (2.6.3)
  - AFNetworking/UIKit (2.6.3):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession

**Comment by poetwang** [comment]
Add pod 'OpenSSL-Universal', '~> 1.0.1.p'

**Comment by scottcc** [comment]
Hmm - your Podfile already designates that as a dependency: Podfile.lock has a `- OpenSSL-Universal (1.0.1.20)` entry (adding the pod line you mention does not change anything after `pod install` either).

**Comment by scottcc** [comment]
I'm open to any other suggestions you might have; thanks for your help so far.

**Comment by poetwang** [comment]
Podfile.lock has a OpenSSL-Universal entry, but this library is a static library. There is something wrong with static libraries dependencies. You have to add the entry pod 'OpenSSL-Universal', '~> 1.0.1.p' before pod 'Seafile', :git => 'https://github.com/haiwen/seafile-iOS.git'

**Comment by scottcc** [comment]
I can add that `pod 'OpenSSL-Universal', '~> 1.0.1.p'` line (and _only_) that, and my project builds just fine. I see this in the Podfile.lock file:

    - OpenSSL-Universal (1.0.1.20)

The moment I add `pod 'Seafile', :git => 'https://github.com/haiwen/seafile-iOS.git'` _below_ that line, I get "Library not found for -lssl" again. My Podfile.lock then looks like this:

    - OpenSSL-Universal (1.0.1.20)
    - Seafile (2.5.1):
      - AFNetworking (~> 2.6.1)
      - OpenSSL-Universal (~> 1.0.1.p)

I've been trying to see what/how your sample application uses this in terms of Embedded Binaries and Search Paths and goodness knows what else in the build section, but still no joy.

**Comment by scottcc** [comment]
So perhaps, reopen issue since it's still unresolved?

**Comment by scottcc** [comment]
Never mind - figured out the issue. The Seafile.podspec needs some changes - submitting a MR for you.
