### ISSUE TITLE
request: allow preview/edit on more or all files with fixed-width font

### ISSUE THREAD

**Issue by tommythorn** [haiwen/seafile-iOS#140]
In Seafile iOS I can preview and even edit certain files, like .c files, but I have many other text files that aren't editable.  Can we loosen the constraint on the file extension and just trust the user to know what files he wants to edit?

Also, why is the preview using a fixed width font but the edit window a variable sized font? (IMO, they should both be fixed width).

**Comment by scottcc** [comment]
+1

**Comment by poetwang** [comment]
Seafile app is not designed for text editing. It only provides a basic editor for some common text files. If you want to edit those files, you can open that file in other apps. There are many apps that can open files from icloud drive. I have already changed the font used in edit window. The new version will be released soon.

**Comment by tommythorn** [comment]
? All I'm asking is that we stop treating a few extensions (like .py .c etc) as magical and allow the same access to all files, regardless of extension.

I'm not aware of any other way to edit seafile files _on the phone_.
