### ISSUE TITLE
App crashes when opening

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#142]
Hi Poet

After the update to 2.5.4 the app crashes after trying to launch it. 

You probably already know that. 

Greetings , Chris

**Comment by fabiodcorreia** [comment]
Same here

**Comment by poetwang** [comment]
some devices may crash, I have already submitted a new version to app store to fix it.

**Comment by GITchristoph** [comment]
Thanks mate

**Comment by GITchristoph** [comment]
Thanks, all fixed in 2.5.5
