### ISSUE TITLE
Feature Request: Add ability sync photos from device to specific folder, instead of specific library

### ISSUE THREAD

**Issue by jamietanna** [haiwen/seafile-iOS#143]
Currently, to sync camera photos from a device (be it Android, iOS, etc) you have to specify a library; however, if there's the option to specify a folder _within_ a library, that would be appreciated.

Expected workflow:

1. Enable auto-sync
1. Select Upload Directory
1. Select Library
1. Select folder within library, OR select done

This would allow a single Library, such as `Photos` that would have a shared set of images, opposed to multiple Libraries, or having potential collisions for the photos between devices.

**Comment by poetwang** [comment]
We do not want to make it too complicated. Just keep it simple.
