### ISSUE TITLE
autoupload - cache doesn't clear on videos?

### ISSUE THREAD

**Issue by bbsmack** [haiwen/seafile-iOS#144]
Cache keeps growing larger and larger when uploading and doesn't clear automatically I think on videos or at least perhaps larger videos.  Pictures I think clear automatically as i see cache moving up and down a lot when uploading and most of the camera roll is pictures.

(Haven't manually tried to upload a video to see if cache clears).

System/App info
On Seafile 2.5.5 but this has always happened since August 2016 when I started using seafile pro.  Seafile server is the latest version available in mid December, on Debian Jessie.

**Comment by poetwang** [comment]
I will check that.

**Comment by poetwang** [comment]
fixed
