### ISSUE TITLE
Feature Request - only show recently updated Libraries

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#145]
Hi!

Client works really good for us. Thanks a lot.

With a growing number of Libraries, it would be handy to have a similar sorting possibility as on the desktop client to show recently updated libraries first, irrelevant to which group they are shared with. 
That helps with the speed when working in iOS.

We think: Absolutely worth considering ;-)

What do you think?

Greetings, Chris

**Comment by poetwang** [comment]
Yeah, that helps if user can see the most recently updated libraries. I would change the default sort order to last-modified-time from library name.

**Comment by GITchristoph** [comment]
In my opinion that's the right way forward. 

Do you know if that would also have an effect on the "open in" dialogue box, e.g when opening a word file from the word.app?

Because I would consider it ideal to sort that dialogue the same way (if iOS allows). 

Chris

**Comment by poetwang** [comment]
Sure, all the library list should behave the same way.

**Comment by poetwang** [comment]
will be fixed in the next version

**Comment by poetwang** [comment]
fixed in v2.5.6
