### ISSUE TITLE
URL Schemes

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#148]
Hi

I have 2 questions about URL schemes.

1.
I want to use Launcher on iOS to open Seafile with a specific Folder. I use this as the URL Scheme but after the Lobrary opened, Seafile.app gives the error message: "Failed to find Folder".
What am I doing wrong?
URL scheme: seafile://openfile?repo_id=4eb3dfhytd-sewf-3wcd-xse2-3912346df9f&path=Folder

2. 
Is there some explanation about the Seafile URL schemes somwhere on the web?

Thanks in advance for your answer,

Chris ;-)

**Comment by GITchristoph** [comment]
Hi poet

Looking into point 1. a bit more, it seems that none of the internal seafile links work on my iOS devices.
Could it be that the functionality is broken?

I am trying to integrate seafile into some automation workflows. This could make Seafile quite powerful. What do you think? Would you have a look at this again?

Regards, Chris

**Comment by poetwang** [comment]
You can try seafile://openfile?repo_id=4eb3dfhytd-sewf-3wcd-xse2-3912346df9f&path=%2F
Yous should use the absolute path here. This is the same link used to open a file via client in the browser.
