### ISSUE TITLE
Searching for an image in the libraries list does not allow you to view it.

### ISSUE THREAD

**Issue by halfsoft** [haiwen/seafile-iOS#151]
When you try to open an image from the search results in the main libraries view the code tries to enumerate all images in the current folder(in order to support swipe to see next image), however as there are no images in the main folder you just get a white screen.

SeafViewDetailController.m: 
> - (void)setPreViewPhotos:(NSMutableArray *)items current:(id<SeafPreView>)item master:(UIViewController<SeafDentryDelegate> *)c
>{
>     if(items.count==0)
>         [items addObject:item];//bugfix for image preview when searching, important it will not support scrolling trough the results

**Comment by poetwang** [comment]
it is a bug, will be fixed soon.

**Comment by poetwang** [comment]
it is a bug, will be fixed soon.

**Comment by poetwang** [comment]
fixed in v2.5.6
