### ISSUE TITLE
Seafile app 2.5.5 unable to add HTTP address for "other server"

### ISSUE THREAD

**Issue by jvandermeulen** [haiwen/seafile-iOS#152]
Seafile iOS app 2.5.5 seems to have no possibility to enter an HTTP address for a "add account / other Server". When the slider is switched from HTTPS to HTTP this does not affect the URL. 

The prefix of the visible URL seems to be locked (except for the last slash, that single sign can be removed). So the locked part seems to be this:
> HTTPS:/

I happened to work around this issue on my iPhone once (iOS 10.2.x) but on my iPad (iOS 10.2.x) it's not possible.

**Comment by poetwang** [comment]
I failed to reproduce this problem. Could you provide more details please? e.g.  screen shot?

**Comment by jvandermeulen** [comment]
When the switch is set from HTTPS to HTTP the "http**s**:" part of the URL is fixed. Observe the single slash in the screenshot.
![img_1012](https://cloud.githubusercontent.com/assets/838001/23023135/554c067c-f454-11e6-8464-a068b9ac26e2.PNG)

**Comment by secure11** [comment]
I am having the same problem with the IOS app on an ipad with 10.2.1 IOS. Using "other server" the toggle can be switched OFF for https. However, the "s" in "https://" cannot be removed in the site URL. It cannot be deleted. In a production environment, we would be using https, but for testing right now, we don't have an SSL certificate installed.

**Comment by timmy59100** [comment]
Same Problem with not removing the "s" in "https://" in the IOS app.
In Android it's working.
