### ISSUE TITLE
Update to Seafile iOS 2.5.6 deleted all accounts and can't login anymore

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#153]
Hi

Updated. Messed up all accounts.
Did a reinstall of seafile.

Can't add accounts anymore.

IPad pro 9.7 inch.
Latest Seafile server 6.0.6 (?)
Latetst iOS.

Maybe something went wrong?

Greetings, Chris

**Comment by poetwang** [comment]
Which version did you update from? v2.5.5?

**Comment by GITchristoph** [comment]
Yes from 2.5.5

I still can't add accounts (all previous accounts got deleted). 
After I added my credentials and clock "login" then nothing happens. 

Kind Regards

Chris




On 15 Feb 2017, at 05:38, poet <notifications@github.com> wrote:

Which version did you update from? v2.5.5?

**Comment by GITchristoph** [comment]
It's true that my accounts got deleted BUT the rest was my fault.
I used the URL https://seafile.mydomain.com/WEBDAV

Obviously in seafile --> don't put the Webdav...

Sorry, all my fault,

Chris
