### ISSUE TITLE
text viewer encoding (autodetect?) issues

### ISSUE THREAD

**Issue by stuntsman** [haiwen/seafile-iOS#155]
I've got an ISO-8859-2 txt file in my library. Even though it's displayed correctly in the web interface (proper encoding name is also shown in upper right corner), in the app it displays only garbled Chinese characters (both in viewer and editor). App version is v2.5.7, iOS 10.2.1.

**Comment by poetwang** [comment]
This charset(ISO-8859-2) does not support Chinese characters. https://en.wikipedia.org/wiki/ISO/IEC_8859-2

**Comment by stuntsman** [comment]
This is still an issue, my report has been misunderstood.

The issue is, that only a few codepages are supported, see `Utils.m`:

```
        NSStringEncoding encodes[] = {
            NSUTF8StringEncoding,
            CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000),
            CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_2312_80),
            CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGBK_95),
            NSUnicodeStringEncoding,
            NSASCIIStringEncoding,
            0,
        };
```

For many codepages the autodetect fails and gives wrong result. You can try Windows-1250, Windows-1252, ISO-8859-1, ISO-8859-2 or many others. ISO-8859 codepages are widely used in European countries.

File in Windows-1250 encoding (simple single byte codepage):

![Screenshot 2020-10-28 18 29 51](https://user-images.githubusercontent.com/2482177/97473748-a10a9900-194b-11eb-9676-b8c60445456e.png)

Failed autodetect in Seafile:

![IMG_4716](https://user-images.githubusercontent.com/2482177/97473652-86d0bb00-194b-11eb-8dec-72799d7aef77.PNG)

**Comment by stuntsman** [comment]
Also attaching the file itself:

[test.txt](https://github.com/haiwen/seafile-iOS/files/5453848/test.txt)

You need to set encoding to Windows-1250 in your editor/viewer to display correctly.
