### ISSUE TITLE
Can not open files 

### ISSUE THREAD

**Issue by PalminX** [haiwen/seafile-iOS#156]
I am using the IOS client 2.5.9 with a 6.0.7 server and have the following problem:
I can browse all Libraries and folders without issue, but when I select a file, it starts downloading, then stays on the download screen instead of displaying the file. 

Like this, the client is kind of useless.

**Comment by PalminX** [comment]
I tried uploading a photo: directly after the upload, I can view the photo in the Seafile client. When I leave and enter the directory again, the photo will not be displayed anymore (the thumbnail is a generic one and selecting it will just show a white screen.

**Comment by Zazub** [comment]
Exactly same problem, 2.5.8 and 2.5.9 ios app version, on iphone SE and iphone 6, on 2 differens server; windows server and linux(debian)  6.0.7 version for linux, the Android on my Tablet work perfectly

**Comment by tmore1** [comment]
Hi everyone,

so I've allready discripe my issue on the Forum (https://forum.seafile.com/t/issue-with-ios-10-3-2/2848/3)
I think the problem exists only on iOS 10.3.2 devices.

Can everybody report, which iOS Version you use, in case of this same error?!
Can anyone solve this problem please?

Thank you all.
With kind regards,...

**Comment by Zazub** [comment]
Hi tmore1 ! my ios version is: 10.3.1

**Comment by PalminX** [comment]
I am on iOS 10.3.2

**Comment by poetwang** [comment]
Is the local decryption enabled?

**Comment by Zazub** [comment]
Enable or not same problem. by default, is not enable.

**Comment by pwellever** [comment]
Same issue here, also iOS 10.3.2. From the Seahub logs, I can see that initiating a download in the app results in a series of identical API requests that look like this:

`[27/May/2017:12:06:17 -0400] "GET /api2/repos/95171b44-1180-4f0b-bbcc-9ac4cc3cd6a4/thumbnail/?size=192&p=/IMG_20170517_205247_0763.JPG HTTP/1.1" 200 41578 "-" "SeafilePro/1 CFNetwork/811.5.4 Darwin/16.6.0"`

This repeats continuously until it gets rate limited:

`[27/May/2017:12:06:17 -0400] "GET /api2/repos/95171b44-1180-4f0b-bbcc-9ac4cc3cd6a4/thumbnail/?size=192&p=/IMG_20170517_205247_0763.JPG HTTP/1.1" 429 82 "-" "SeafilePro/1 CFNetwork/811.5.4 Darwin/16.6.0"`

**Comment by Miller101** [comment]
#158 

https://github.com/haiwen/seafile-iOS/pull/158#issuecomment-304534377
Fixed it.

**Comment by poetwang** [comment]
fixed in 2.6.0
