### ISSUE TITLE
iOS app roadmap

### ISSUE THREAD

**Issue by masipcat** [haiwen/seafile-iOS#157]
Hi,

Where can I find a TO-DO list to contribute this project?

Thank you,

**Comment by freeplant** [comment]
We don't have a public todo list. Current the most urgent work is improving photo auto-backup (for 1000+ photos) and improve file preview. You can find  a issue for file preview here: https://github.com/haiwen/seafile-iOS/issues/156 . It is much appreciated if you can help.

**Comment by masipcat** [comment]
I'll check it!
