### ISSUE TITLE
App crashes on opening PDF on iPhone 4S

### ISSUE THREAD

**Issue by mst226** [haiwen/seafile-iOS#163]
After upgrading to 2.6.1, the app opens normally and login also succeeds. But when I try to open a PDF or TXT file, the app downloads the file and dies when it tries to open the document.
Access to JPG and other pictures is working fine.
I'm using an iPhone 4S with iOS 9.3.5. My account is on a private Seafile server (CentOS 6, 5.0.5, x86_64).

**Comment by poetwang** [comment]
Should be fixed in v2.6.2
