### ISSUE TITLE
Download of libraries / folders not usable

### ISSUE THREAD

**Issue by querteru** [haiwen/seafile-iOS#169]
When I try do download a complete library or a folder within the iOS client (v2.5.3, but also previous versions) to make it available offline, it loads very slowly. More importantly, when the download is interrupted (app closed, screen locked), it does not resume next time I open the app. Also, the download progress is not shown and there is no way to tell whether the download is completed.
This renders the feature to download libraries / folder unusable. Are there any plans to improve this?

**Comment by freeplant** [comment]
Yes, we are improving it currently.

**Comment by querteru** [comment]
Great, looking forward!

**Comment by Miller101** [comment]
Hi 👋🏻 
Any news on this?
Latest update from this week stilm faces it :/

**Comment by freeplant** [comment]
The latest version is supposed to fix the problem. As I tested just now, the download of a folder should work. There is also a new "Download/Upload" section in settings to show the progress of download.
