### ISSUE TITLE
Files cannot be opened via Photo Browser

### ISSUE THREAD

**Issue by dave-fl** [haiwen/seafile-iOS#184]
The photo browser is an excellent tool to easily allow you to browse images. Unfortunately if you want to print a file you need to remember the file name and then open the file. 

There should be a shortcut link of some sort that allows you to open the original file directly in the full view of the photo browser so it can be shared, printed, saved to an album etc.

**Comment by poetwang** [comment]
will be added in the next release.

**Comment by poetwang** [comment]
fixed in 2.6.10
