### ISSUE TITLE
Unify release number

### ISSUE THREAD

**Issue by egroeper** [haiwen/seafile-iOS#186]
It seems like there are several locations in the code containing a static release number.

The current release (2.6.8) seems to contain release numbers between 2.6.2 and 2.6.7 (not sure, if 2.6.8 is somewhere).

I stumbled upon the issue, when I had a look at the api2_tokenv2 table of our installation to see which versions our users are currently using.
A freshly created auth-token with 2.6.8 results in a version entry 2.6.2.

**Comment by poetwang** [comment]
fixed in 2.6.9
