### ISSUE TITLE
Xcode9 shows odd tableview cell label heights

### ISSUE THREAD

**Issue by scottcc** [haiwen/seafile-iOS#187]
Hello there. Just wanted to check whether you guys see this as well when compiling/running your application under Xcode9? From what I can see, the labels in the `SeafFileViewController` are having an odd vertical squishing effect, regardless of the simulated iOS version you run on.

As an example, I see this:

![label-clips](https://user-images.githubusercontent.com/225380/30866028-24268440-a2a6-11e7-98b4-5deb4e79daf3.png)

If you compile against the iOS 10 SDK, no problem. Have you guys seen this?

**Comment by scottcc** [comment]
Huge fan by the way; great system you have here.

**Comment by scottcc** [comment]
Closed and resolved?

**Comment by lilthree** [comment]
resolved
