### ISSUE TITLE
Feature Request - Move files

### ISSUE THREAD

**Issue by Gronis** [haiwen/seafile-iOS#188]
I've been looking into changing to seafile, but the IOS app still needs a few basic features which are not yet implemented. For example, moving files.

For this feature to work smoothly, a simple select feature should also be added. Then a user can select and move several files at once. The select feature could also be used to delete several files at once or download multiple files at once.

**Comment by poetwang** [comment]
The iOS app does support move function. You can click on the right top button, a menu will show up, choose the "Edit", then you can choose multiple files to copy, move or delete.
![img_2f09c4852819-1](https://user-images.githubusercontent.com/1908737/31003564-3b82657c-a4a5-11e7-8381-eb766c851d69.jpeg)
![img_f9a8072baa32-1](https://user-images.githubusercontent.com/1908737/31003569-40fd756e-a4a5-11e7-815a-425743807462.jpeg)
