### ISSUE TITLE
.heic 格式图片

### ISSUE THREAD

**Issue by kosmgco** [haiwen/seafile-iOS#189]
OS: iOS 11
Internet: WIFI

Seafilepro 中 `Settings` > `CAMERA UPLOAD` 选择`Auto Upload` 不能上传`*.heic` 格式的图片。

**Comment by alperozcetin** [comment]
@kosmgco You have closed this issue, but were you able to fix it? I'm having the same problem in 2023. :) No means to upload HEIC.
