### ISSUE TITLE
Files not uploading

### ISSUE THREAD

**Issue by klein-j** [haiwen/seafile-iOS#192]
I'm trying to synchronize my Photos from my iPhone. First I tried the auto upload feature, which uploaded around 10 of my pictures but then stops. I tried to restart it multiple times, but could not get it running again. So I tried the manual upload, but it did not start either. I can see the images in the upload queue, but all it says is "Waiting to upload". I would love to give more details, but I can't, as the app does not give me any (which is also an issue that should be fixed).
I'm using the iPhone App Version 2.6.10 and my custom Seafile server, which runs fine on really every other device (it runs version 6.0.7 - I did not see any iPhone related bug fixes in the release log and don't want to update it right now, as I do not have physical access to it in case something goes wrong).

**Comment by poetwang** [comment]
Did you upload to an encrypted library or unencrypted? Did you enable local decryption?

**Comment by klein-j** [comment]
I'm uploading to an unencrypted library (and thus should not have local encryption). Any other helpful information I could provide, or anything I could try out? Possibly some server logs?

**Comment by poetwang** [comment]
The server log would be perfect, can you find some error message in the seafile server, file upload related?

**Comment by sNNNeaker** [comment]
Same Problem here. If you turn off and on the location services for the seafile app, the upload works once
