### ISSUE TITLE
Background Upload toggle always switching itself off again

### ISSUE THREAD

**Issue by c0d1ng** [haiwen/seafile-iOS#194]
Turning on the Background Upload setting for Camera Upload doesn't seem to stick.
If I switch to the library tab and go back to settings, the toggle is switched off again.
Using iOS 11.1.2

**Comment by vectr0n** [comment]
I am also seeing this behavior. Running Seafile Pro 6.2.1 with Seafile Pro iOS App 2.6.10 on an iPhone 7 128GB with iOS version 11.2.

**Comment by Admonstrator** [comment]
Same behavior on iPhone X with iOS 11.2

Seems to be an issue with the GPS hook because you need it to enable upload automatically. Seafile is not registering on the GPS module in iOS - this should be the problem in that case.

**Comment by lilthree** [comment]
will be fixed in the next release

**Comment by Admonstrator** [comment]
Any chance that this release will be available in the next few days?
It's really annoying because the app keeps crashing even if you disable the upload ... :/

**Comment by lilthree** [comment]
fix in 2.7.1
