### ISSUE TITLE
iOS app 2.7.0 does not allow drag and drop, favourite or tags

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#200]
Hi Poet

Thanks so much for implementation into iOS files.app

Unfortunately it‘s not easy to use because it does not allow drag and drop, favourite or tags. 
May i ask if it‘s planned to be implemented?

Upload works via the normal way, but not via drag and drop.

Let me know if you need any testing done if that supports you. I am glad to help wothon my capabilities ;-)

Chris

**Comment by poetwang** [comment]
we are still continuing improve favourite, tags

**Comment by GITchristoph** [comment]
So cool and am very excited ;-)

Cheers!
