### ISSUE TITLE
IOS 11.2.1 Files App size 0 KB and date 1.1.70

### ISSUE THREAD

**Issue by mburgholte** [haiwen/seafile-iOS#201]
I have a fresh install of the seafile app (2.7.0). I use my seafile server amongst other things for a password safe. If I want to open my safe for the first time I can see it correctly inside the files app
and in pwsafe 2 app. If I want to load my safe, the app tells me, that this file is not existent. Inside the files app my safe has now a size of 0 KB and a date of 1.1.70. WTF?! Inside the seafile app
everything is fine (size and date). Is it a bug inside the files app or what do you think? I thought it is a bug inside pwsafe and wrote them my bugreport. They think it is a bug inside the seafile app. [...] This looks like a bug in the seafile app, more specifically inside its file provider extension. I suggest you uninstall seafile, reboot your device and then reinstall it.[...] I reinstalled the app and did the reboot but the bug is still present. Thanks in advance.

**Comment by onekreg** [comment]
I’ve got the same problem while opening a file with excel through the files app on my seafile cloud.  When I click save in excel everything gets saved correctly.  But when I try to open the file  again it’s impossible. The size changed in files 0 kB the date is 1.1.1970.  The fire can only be accessed again after rebooting the iOS device.
I think there’s a bug  in the saving process.

**Comment by mburgholte** [comment]
Great to hear that someone has exact the same problem. Hope we get help soon.
