### ISSUE TITLE
Possible-Bug: AutoUpload is freezing after 2 Pictures 

### ISSUE THREAD

**Issue by sNNNeaker** [haiwen/seafile-iOS#202]
Hi @all,

My wife’s SeafilePro App freezes after it auto uploads 2 pictures. Every time, it is reproducible. 
That is not very fun with 240 pictures to go.
iPhone 7 - iOS 11.2.1
SeafilePro 2.7.1 App

Strangely my iPhone SE with the same software versions works.

Please help :)

Thanks in advance!

**Comment by freeplant** [comment]
What do you mean by freeze? Does it not upload more pictures or the whole App crash?

**Comment by sNNNeaker** [comment]
The App is frozen. That means you can’t scroll or click on anything. After a long while the app eventually crashes (it closes and you are back on the iOS home screen). That only happens if you are in the settings screen where you see the total number of pictures to upload and/or if all pictures are synced.

If you are in the library screen, it doesn’t freeze but stops uploading after 2 pictures and crashes too after a long while.

Hope that makes sense.

Tried reinstalling and restarting the app and phone, didn’t help.

Is there any way to collect logs on the phone?

**Comment by lilthree** [comment]
I will check this problem and try to fix it.

**Comment by Admonstrator** [comment]
I can confirm this bug on iPhone X using iOS 11.2.5 Public Beta 2 and Seafile app 2.7.1

**Comment by kosmgco** [comment]
me too.
iOS 11.2.1 with seafile-ios latest version

**Comment by lilthree** [comment]
Does it happen on iOS11.1 or iOS11.0?

**Comment by sNNNeaker** [comment]
It worked back in October. So it might broke with 11.1 or 11.0.3, I’m not 100% sure.

**Comment by sNNNeaker** [comment]
@lilthree any updates on the status?

**Comment by sNNNeaker** [comment]
We uploaded our 240ish pictures through the computer. Now we have 10 to upload, it’s still freezing/crashing after 2 pictures auto uploaded.

Please update on the status.

**Comment by freeplant** [comment]
The fix will be available in the next release in this week.

**Comment by Admonstrator** [comment]
@freeplant Which version is the next release?
In 2.7.2 on iOS 11.2.5 the issue does still exist.

**Comment by lilthree** [comment]
2.72 is the release that has fixed it，it doesn't exist on my device，could you reinstall it

**Comment by Admonstrator** [comment]
@lilthree 
Reinstalled the app, still the same: While uploading with auto-upload enabled the app keeps crashing.

**Comment by scottcc** [comment]
Hey @Admonstrator - just a wild, crazy thought here. I'm a big fan (and user) of this project but am not involved with haiwen in any way (just to be up front). Curious if you have Xcode installed? If you do, and you plug your phone in, the "Devices and Simulators" menu you could look to see what kind of crash information you have there for Seafile. Might be helpful if you have it.

**Comment by Admonstrator** [comment]
@scottcc Thanks for your hint - unfortunately I am a Windows user so no Xcode available :(

**Comment by lilthree** [comment]
@scottcc thanks for your suggestion, @Admonstrator may be you can find the crash information on your iPhone, open 'Setting'->'Privacy'->'Analytics'->'Analytics Data',there could be a row called 'Seafile Pro ********.ips'.If you find it ,please send it to me, zhaolilthree@gmail.com,thanks a lot.

**Comment by Admonstrator** [comment]
@lilthree Sorry to say so but even after a crash there will be no dump file.
Other idea?

**Comment by lilthree** [comment]
@Admonstrator  Have you ever turned on the Upload-Videos switch?

**Comment by Admonstrator** [comment]
@lilthree Yup.

**Comment by lilthree** [comment]
fix in 2.7.3,it will be available in this week.
