### ISSUE TITLE
Uploaded files don’t show up in the files app

### ISSUE THREAD

**Issue by onekreg** [haiwen/seafile-iOS#207]
Hello,

If I upload a file with the iOS files app it will never shows up in the files app, even though it will be handeld correctly by the seafile app. You can access it from the seafile app too. There is just no feedback about a new file for the files app.

I am using ios 11.2.5 and seafile 2.7.3.

**Comment by poetwang** [comment]
will be fixed in next version

**Comment by lilthree** [comment]
fix in 2.7.5
