### ISSUE TITLE
Not possible to create a new file everywhere but in a root of an library.

### ISSUE THREAD

**Issue by 34x** [haiwen/seafile-iOS#214]
Hi, 

I have a few libraries (not encrypted) and for all of them after clicking on three dots icon on the right top corner I have menu item `New file`, but if I go deeper even one more level, let's say: `Library-name/foo` after clicking on three dot's there is no `New file` item.

Ho to reproduce:
 - Open app
 - Open any library
 - Open a folder on the first level inside the library
 - Click on `...`  on the right top corner

Expected:
There is a menu item `New file` appears.

Actual:
No `New file` menu item.

Seafile iOS client 2.7.6
iOS 10.3.2

**Comment by lilthree** [comment]
I will fix this problem as soon as possible
