### ISSUE TITLE
Getting error. Unable to build.

### ISSUE THREAD

**Issue by omkarnathsingh** [haiwen/seafile-iOS#216]
[!] Unable to find a specification for `SVProgressHUD (~> 1.1.3)`
 
When I am running "pod install", i get above error. any help?

**Comment by lilthree** [comment]
Try running 'pod repo update',then 'pod install'.

**Comment by omkarnathsingh** [comment]
Thanks. It helped me.

**Comment by omkarnathsingh** [comment]
/Users/omkar/Projects/seafile-iOS/SeafFileProvider/SeafEnumerator.m:9:9: In file included from /Users/omkar/omkar/seafile-iOS/SeafFileProvider/SeafEnumerator.m:9:

/Users/omkar/Projects/seafile-iOS/SeafFileProvider/SeafEnumerator.h:10:9: 'FileProvider/FileProvider.h' file not found

This header file is not found. Any clue?

**Comment by lilthree** [comment]
Select 'SeafFileProvider' Target->'Build Phases'->'Compile Sources',and click '+'，add FileProvider.h

**Comment by omkarnathsingh** [comment]
I am on Xcode 8, I guess thats the issue. Above thing, didn't help me.

**Comment by lilthree** [comment]
Maybe you need to upgrade to Xcode 9

**Comment by omkarnathsingh** [comment]
Builds on Xcode 9. Thanks.
