### ISSUE TITLE
iPhone SE files list scrolls to high after refresh

### ISSUE THREAD

**Issue by 34x** [haiwen/seafile-iOS#217]
Hi, 

After the last update the issue appeared in the file browser. 

After opening the app file browser screen is fine, but after pulling the list and refreshing content it goes too high, so the first folder is partially overlapped.

I found that in a simulator (also SE) there is a search field added (on my real device I did not). So in case of a simulator scroll view scroll almost to hide the search bar, in case of a real device it provides a bug.

The first screen is initial state, and the second one is after refresh.
![fullsizerender 2](https://user-images.githubusercontent.com/60165/41252639-0a3624a8-6dbe-11e8-9c06-7891ab072eb7.jpg)
![fullsizerender](https://user-images.githubusercontent.com/60165/41252641-0a64ca24-6dbe-11e8-9a9f-c13bd0eed83c.jpg)

P.S. I assume the problem is about on my device search field is somehow missed.

iPhone SE
iOS 10.3.2
Version 2.7.7

Best regards,
Maks

**Comment by lilthree** [comment]
Will fix in next version
