### ISSUE TITLE
Crashes when opening in iOS12 beta1.

### ISSUE THREAD

**Issue by ojbgame** [haiwen/seafile-iOS#218]
Crashes when opening in iOS12 beta1,even after restart or reinstall. Maybe compatibility problem.
Please fix it, thank you!

iPhone 6S plus
iOS 12 beta1
Version 2.7.7

**Comment by lilthree** [comment]
It run well on my device, also using iOS 12. I will find out where the problem is.

**Comment by ojbgame** [comment]
Now the app doesn't crash in iOS12 anymore.
