### ISSUE TITLE
Feature Request save multiple photos with the photos app to seafile

### ISSUE THREAD

**Issue by satheras** [haiwen/seafile-iOS#221]
Dear Seafile Team!

Please add import/share functionality  as e.g. dropbox or nextcloud are already having implememted. I am considering this as a must have core functionality that seafile is lacking.

How should it work for the user:
The user goes under ios photos and presses the share button. In the first line with those app icons the yellow seafile app icon appears. The user can select multiple pictures/videos from the ios photo app —> the yellow seafile app icon stays. By pressing on the app icon the import to seafile will be guided to select/create the folder to save to.

For instance: if you try to save a pdf through the mail app in seafile you can already see my wanted app icon in the first bar! But for whatever reason this functionality seems not to be diasabled or broken for photos! 

Today it is only possible to save one photo and you have to search for this possibility in the second bar under those app icons. You have to look for a grey symbol... and that is odd because you can‘t import multiple.

Please integrate this new features! I am sure many customers and the community would appreciate it! Since it is such a common and expected feature after using dropbox or nextcloud for several years.

Running in iphone 7plus/IOS 11.4.1

Thanks!!

**Comment by freeplant** [comment]
We will look into the issue.

**Comment by satheras** [comment]
This seems to be fixed with the only limitation of 10 files maximum. With the 11th photo the seafile icon is disappearing. But that seems to be an IOS limitation!
