### ISSUE TITLE
Possibility to share more than one picture directly through whatsapp, messenger and so on

### ISSUE THREAD

**Issue by satheras** [haiwen/seafile-iOS#224]
Hello,

At this time it is only possible to share a single picture from within the app with the share button.

Would be great if you could just select more pictures at a time and just invoke the share functionality to whatever apps are compatible (like whatsapp, messenger and so on)

Thanks in advance

**Comment by lilthree** [comment]
Available in 2.7.9

**Comment by satheras** [comment]
Thanks! Confirmed!

**Comment by satheras** [comment]
Thanks! But i did not find how i can do that. Please could you explain?

I tried it like this:

https://imgur.com/gallery/IdarILm

But there isnt a button.

Best wishes satheras

**Comment by lilthree** [comment]
Sorry,I mistakenly think it‘s the same as #225

**Comment by lilthree** [comment]
Available in 2.8.2
