### ISSUE TITLE
Photo upload option, photo album didn't get completely, a total of 986 images, upload shows only 200 images

### ISSUE THREAD

**Issue by MjzDk** [haiwen/seafile-iOS#227]
ALasset access to the photo album is incomplete.
update Podfile 'QBImagePickerController'  (new -> 3.4.0  old ->2.2.2)  can get to all of the pictures,
in 'QBImagePickerController'  use PHAsset  ,  but seafile in Class 'SeafUploadFile' use ALAsset.
Version: iPhone8P  iOS 11.4

**Comment by lilthree** [comment]
I will update this in the next few days.
