### ISSUE TITLE
Feature Request: Sync favorites with Server

### ISSUE THREAD

**Issue by sNNNeaker** [haiwen/seafile-iOS#230]
Hi,
Working great here so far. It would be nice tho if the fav get synced with the server.

**Comment by freeplant** [comment]
What do you mean by Sync favorites with Server? Do you favorite a file in iOS File App?

**Comment by sNNNeaker** [comment]
Basically if we fav pictures on the seafile iOS app, we would like that flag to be synced to the windows/Mac client. Kinda like iCloud Favorites

**Comment by gkivanov** [comment]
Starring a file in the iOS client is also reflected in the browser client. Tested on iOS app version 2.8.1 and server version 6.3.4.

**Comment by sNNNeaker** [comment]
Yes that is true. But we here mostly use the Mac/Windows and iOS Clients..

**Comment by gkivanov** [comment]
Starred files also appear correctly in the `Starred Files` tab of the macOS client. I would assume it also works in the Windows client. Do you envision files being somehow starred in Finder as well?

**Comment by sNNNeaker** [comment]
Wrong Information..sry

We fav. a Photo within the iOS Photo Library. That should (or be able to activate that feature) be a starred file within Seafile (iOS/mac/windows).

**Comment by gkivanov** [comment]
So your feature request is: Uploading **photos** marked as favourites be marked as starred in Seafile.
