### ISSUE TITLE
Rename a folder within the app with preserve the name

### ISSUE THREAD

**Issue by satheras** [haiwen/seafile-iOS#233]
Dear Seafile Dev community!

It would be great if the renaming function of a folder or a file would preserve the current file/foldername in the typefield.

If i create a folder currently and for instance make a typo i would have to write everything again instead to just fix the typo.

Thanks in advance

**Comment by Joshh864** [comment]
thumbs up on this

**Comment by lilthree** [comment]
Added to 2.8.1

**Comment by satheras** [comment]
Works! Thank you

**Comment by Joshh864** [comment]
Very nice I like this feature as well!

Josh Horowitz
