### ISSUE TITLE
Search function not there anymore in IOS App

### ISSUE THREAD

**Issue by satheras** [haiwen/seafile-iOS#234]
I cant find the search function from within the app anymore.

seafile pro 6.3.7 server
Seafile IOS App: 2.8.0
IOS 12 on Iphone and IOS 12.1 on Ipad

https://imgur.com/gallery/gUpWWKb

I even reinstalled the app on the devices.
In the webapp the search function is there and working.

**Comment by Joshh864** [comment]
I have the same exact issue.  

Any ideas what's going on?  

iOS app version: 2.8.0
Seafile Pro Server version 6.2.13

Like OP, tried reinstall to no avail on iOS devices.  

Search also working fine on web app.  

What's going on here?  This is an important feature, hopefully can get resolved ASAP.

**Comment by satheras** [comment]
i am just guessing. But i am pretty sure it is related to the latest app update.

**Comment by freeplant** [comment]
We will upload a new version soon.

**Comment by Joshh864** [comment]
Thx Daniel!

Any ballpark on time frame?

Roughly... 

Josh Horowitz

**Comment by freeplant** [comment]
We will publish a new version in this week.

**Comment by satheras** [comment]
Works!! Thank you!
