### ISSUE TITLE
Unable to login to custom server

### ISSUE THREAD

**Issue by danielbyon** [haiwen/seafile-iOS#240]
I am unable to add a custom server. I'm running a server on my own domain, and everything in the web UI works properly, and I can login on Firefox on my iPhone, but cannot login through the app.

My seafile URL is setup to be `https://www.example.com/seafile`

I've used these guides:
https://manual.seafile.com/deploy/using_mysql.html
https://manual.seafile.com/deploy/https_with_nginx.html
https://manual.seafile.com/deploy/deploy_seahub_at_non-root_domain.html

In the seahub.access.log, I see a line that says:
`- some_ip_address [29/Jan/2019:01:57:05 -0800] "GET /seafile/api2/auth-token/ HTTP/2.0" 405 40 "-" "SeafilePro/2 CFNetwork/978.0.4 Darwin/18.5.0" 0.008`

This looks like an HTTP 405? Which is a Method Not Allowed (not sure what that means).

I'm running Seafile version 6.3.4 on Ubuntu 18.04.

**Comment by freeplant** [comment]
I think this is a config problem. I suggest you try to not use a non-root domain configuration.
