### ISSUE TITLE
iOS 9.3.2: no media is played back

### ISSUE THREAD

**Issue by sclemenz** [haiwen/seafile-iOS#253]
Since the last update to version 2.9.0 it's not possible to play back audio or video in the seafile client anymore. The page remains white and nothing happens. The system is iOS 9.3.2 on iPhone 6.

**Comment by TakeMeNL** [comment]
Same here, 2.9 client iOS 12.4 iPhone X

**Comment by lilthree** [comment]
Will be fixed in the next version.

**Comment by sclemenz** [comment]
Sorry it still does not work after the update to 2.9.1

**Comment by moetiker** [comment]
in my case it's working now
