### ISSUE TITLE
iOS v2.9.0: .txt preview not shown on iPhone, no problems with iPad

### ISSUE THREAD

**Issue by M4st3rITA** [haiwen/seafile-iOS#254]
Since latest version 2.9.0 when I try to open (without edit) a .TXT file, I can see a white/blank page; the content of .TXT files is displayed only when I try to edit them.
I cannot reproduce this issue with an iPad because everything goes well.
I never had this problem with previous versions.

**Comment by freeplant** [comment]
It will be fixed in the next release.
