### ISSUE TITLE
Library list not visible in portrait mode on iPad (6th/7th generation)

### ISSUE THREAD

**Issue by moschlar** [haiwen/seafile-iOS#259]
When the app is started on an iPad (6th/7th generation) in portrait mode, the library list in the side bar is not shown. Only when rotating to landscape mode, it becomes visible.
And only after rotating back to portrait mode the top bar link to show them becomes visible.
So the first impression to a user is something broken.

I can't attach a screenshot currently.

**Comment by lilthree** [comment]
Is it running on iPadOS 13？

**Comment by moschlar** [comment]
Yes - its 13.1.2.

**Comment by moschlar** [comment]
Any updates on this?

**Comment by freeplant** [comment]
The fix will be included in the next release.
