### ISSUE TITLE
IOS 13 / Iphone 11 Pro

### ISSUE THREAD

**Issue by satheras** [haiwen/seafile-iOS#268]
Dear seafile community.

Since i switched to an iPhone 11 pro (IOS 13.2.3) i got a new issue regarding the ui.

When i share a file through seafile i cannot update the folder anymore when i am sliding with my finger down... thats because slidingbthe finger down makes the share gui dissappear...

You are all used to this slide down feature in several other apps. This sliding down means most of the time „update page / reload page“ for instance in chrome.

This was different on an iphone 7 plus - also with ios 13. thats also different on an iphone se with latest ios.

Click on the seafile icon
![2A7F8F0D-41C0-4479-93CC-2115F43477F0](https://user-images.githubusercontent.com/36051167/70309898-d62b6b80-180e-11ea-9a52-cda6080498eb.jpeg)

![8864DF5D-4002-4B89-BC40-2DE9878CFDAD](https://user-images.githubusercontent.com/36051167/70309565-1a6a3c00-180e-11ea-9c32-2aac4afcd552.jpeg)

Now drag down..

![7EE8A456-69AE-4A6D-9F39-EC7315179EEB](https://user-images.githubusercontent.com/36051167/70309985-f824ee00-180e-11ea-958e-846fbd5c9a68.jpeg)

And if you drag down a little bit more the seafile gui overlay is vanished. 

Would be glad to have that back again.

Best regards and thanks in advance
satheras

**Comment by satheras** [comment]
If you would do that directly in the app it works as expected...
![4167CD7F-F933-42CF-B3A2-DE3FBD673F2D](https://user-images.githubusercontent.com/36051167/70310414-e1cb6200-180f-11ea-8887-4a9089d7fdaf.jpeg)

**Comment by lilthree** [comment]
I‘ll fix it in next version.

**Comment by satheras** [comment]
Thank you! 👍

**Comment by satheras** [comment]
I can confirm that this has been fixed! Very much appreciated! Thank you!!
