### ISSUE TITLE
on iPhone 5, automatic photo upload doesn't work

### ISSUE THREAD

**Issue by chrislibuilds** [haiwen/seafile-iOS#37]
Version info:

iPhone 5 - iOS 8.1
Seafile Server (self-hosted, CommunityEdition) 3.1.7 (x64 Linux)

Description:
- "Auto Camera Upload" is always enabled in the settings of the iOS App
- clicking on "Upload Destination" doesn't show a popup or does anything at all

Steps taken:
- reinstalling the iOS app & recreate account(s) -> no change
- restarting the phone -> no change
- tested on different hardware -> working on iPad Air with iOS 8.1
- updated server version from 3.1.5 to 3.1.7 -> no change
- checked/removed/re-added permissions to access the photo library
- tried all of the above via Edge, UMTS & Wifi -> no changes

please advice, happy to help.

regards, 

chris

**Comment by hutzla** [comment]
I have the same problem (still? again?) in iPhone 5 and iPad 4 app (both iOS 8.4). Clean installed seafile server version 4.3 pro.

**Comment by hstolte** [comment]
@poetwang I also have the problem on iPhone 5 and iPad 4. iOS 9.2.1 and Seafile pro app-version 2.1.6

**Comment by moritz31** [comment]
Same problem here on iOS 9.x

**Comment by poetwang** [comment]
It is a bug. You can try kill seafile app and then start it again. Will be fixed in the next version.

**Comment by carriercomm** [comment]
Eta on the next version? Still occurs for me on the latest iOS version with 6 Plus.

**Comment by poetwang** [comment]
@carriercomm what is the behavior of your device, and wha tare the steps to reproduce it?
