### ISSUE TITLE
Crash while trying to edit a file

### ISSUE THREAD

**Issue by MichiDoe** [haiwen/seafile-iOS#41]
Hi,

i am using Seafile Client 1.9.1 on iOS 8.1.2 (iPhone 5s, iPad Air).
If i select a file by pressing it for a while or click the edit button on the top, the app crashes immediately. This manner was also in previous versions of Seafile client and iOS.
The filetype is irrelevant.

Could you please have a look at this issue.

Thanks
Michael

**Comment by poetwang** [comment]
I can't reproduce the problem, did it occures in both iPhone and iPad?

**Comment by MichiDoe** [comment]
It happens only at the iPad Air 1 at the moment. iPhone works well. I have three libraries.One of them is encrypted. Is it working in landscape an upended mode on your iPad?

**Comment by poetwang** [comment]
Yes , it works well on my iPad.

**Comment by MichiDoe** [comment]
with the new 1.9.3 version the issues seems to be fixed. file edit works in upended and landscape mode
