### ISSUE TITLE
feature request: Seafile mobile client (iOS/Android) should switch to landscape mode if turn the device 90 degrees

### ISSUE THREAD

**Issue by peters77** [haiwen/seafile-iOS#42]
Hi,

maybe it's just an open request...but it would be really nice if the seafile client would switch into landscape mode and use the space to fit into if I turn the mobile device 90 degrees. 
Should work for pdf, xls or jpg files I am viewing. 
On IPhone only a fixed portrait mode is available, no auto switch into landscape?!

Regards,

Christian

**Comment by poetwang** [comment]
done

**Comment by peters77** [comment]
Just downloaded and tested! Great. Thank you very much, great improvement! :-)
