### ISSUE TITLE
iPhone5s, IOS-client 1.9.1, camera auto upload not working...

### ISSUE THREAD

**Issue by peters77** [haiwen/seafile-iOS#43]
Hi,

Folder was created (Camera Uploads) but taken photos didn't upload. 
Own Seafile-Server V 4.0.2, https connection, IPhone 5s, iOS 8.1.2

Regards,

Christian

**Comment by poetwang** [comment]
Can you upload photos by choosing photos manually？

**Comment by peters77** [comment]
I checked again and I noticed I have to enable photo access in preferences on the IPhone. Would be nice to have a hint if I switch on auto photo upload inside the seafile IOS client to allow access to photos. 
Now it's working. Thumbnails would be a nice feature to implement in a future release!? 

Thank you very much.

Regards,

Christian

**Comment by poetwang** [comment]
Yes, the feature will be implemented soon.
