### ISSUE TITLE
app 1.9.1 crashes with untrusted certificates

### ISSUE THREAD

**Issue by dirkuos** [haiwen/seafile-iOS#44]
seafile app 1.9.1 on iOS 8.1.2
If the seafile server doesn't provide a valid and trusted certificate, the app immediately crashes when trying to bind to the server. For example, I forgot to include the certificate chain in the certificate file that is used by nginx. After including the chain, the app works.

**Comment by poetwang** [comment]
The bug is fixed in 1.9.2
