### ISSUE TITLE
multiple file upload fails

### ISSUE THREAD

**Issue by dirkuos** [haiwen/seafile-iOS#45]
seafile app 1.9.1 on iOS 8.1.2, seafile server 4.0.4 and 2.1.5
When uploading multiple files at once, only the first three files are correctly transferred to the server. All other files are visible, but they have a size of 0 bytes.

**Comment by githubtobi** [comment]
same issue here - iOS 8.1.2. iPhone 5. http or https. Seafile installed on a hummingboard connected via LAN.

**Comment by poetwang** [comment]
it is a bug, will be fixed soon.

**Comment by poetwang** [comment]
fixed in 1.9.3
