### ISSUE TITLE
Remove the gray background from the last selected item

### ISSUE THREAD

**Issue by bst27** [haiwen/seafile-iOS#53]
I see no advantage in making the background of the last selected item gray. I think this should be removed.

![2015-02-05 15 56 31](https://cloud.githubusercontent.com/assets/6805736/6063055/b42206d6-ad54-11e4-870f-8f9ba15122f6.png)
![2015-02-05 15 56 35](https://cloud.githubusercontent.com/assets/6805736/6063056/b612842a-ad54-11e4-889c-d0bd6261b2ff.png)

**Comment by poetwang** [comment]
sounds good

**Comment by bst27** [comment]
I am not sure whether this was changed in the newest version. But if so then it is not working - at least for me.
