### ISSUE TITLE
Pending uploads disappear on update

### ISSUE THREAD

**Issue by bst27** [haiwen/seafile-iOS#54]
My device is an iPhone 5S with iOS 8.1.2 (12B440) installed and Seafile version 1.9.4 with seacloud.cc account.

When I want some pictures to be uploaded they are shown as pending:
![2015-02-05 15 58 31](https://cloud.githubusercontent.com/assets/6805736/6063119/1aec29d2-ad55-11e4-92ac-083da0f05663.png)

Triggering an update by pulling down the window makes some of these items disappear:
![2015-02-05 15 58 36](https://cloud.githubusercontent.com/assets/6805736/6063134/4847fc80-ad55-11e4-936a-7f49007e2e71.png)

After some time they just appear again (I think when they are uploaded):
![2015-02-05 16 03 26](https://cloud.githubusercontent.com/assets/6805736/6063154/6d7423f8-ad55-11e4-9c52-8e5710ddf64c.png)

**Comment by poetwang** [comment]
Yes, it is a bug, will be fixed soon.

**Comment by bst27** [comment]
Seems to be fixed in new version.
