### ISSUE TITLE
App crashes after selecting files for upload

### ISSUE THREAD

**Issue by bst27** [haiwen/seafile-iOS#55]
My device is an iPhone 5S with iOS 8.1.2 (12B440) installed and Seafile version 1.9.4 with seacloud.cc account.

The app just crashes after selecting one or several files for upload. This is reproducible, so I am really not able to upload files at the moment. After selecting some images for upload, I press the button "fertig" and the app crashes. This happens in every library and (sub-)folders

**Comment by poetwang** [comment]
Yes, it happens in "My Photo Stream", will be fixed soon.

**Comment by bst27** [comment]
Seems to be fixed in new version.
