### ISSUE TITLE
App crashes on startup on iPhone 4

### ISSUE THREAD

**Issue by hysan** [haiwen/seafile-iOS#56]
After upgrading to 1.9.4, the app crashes when I try to open the program. I'm using an iPhone 4 with iOS 7.1.2. My account is on a private Seafile server (Linux, 4.0.6, x64).

**Comment by freeplant** [comment]
Version 1.9.4 has problem with iOS 7 (OK with iOS 8). The new version is on the way.

**Comment by hysan** [comment]
Good to hear. I'll be waiting for the next version then. Thanks!
