### ISSUE TITLE
App crashed after upload

### ISSUE THREAD

**Issue by bst27** [haiwen/seafile-iOS#57]
My device is an iPhone 5S with iOS 8.1.3 (12B466) installed and Seafile version 1.9.6 with seacloud.cc account.

The app crashed after upload of file 3516 finished. A was able to see the "file ... has been uploaded" info for a fraction of a second:

![](http://i.imgur.com/IFSScWU.jpg)

After restarting the app pending uploads 3338 and 3087 were removed: 

![](http://i.imgur.com/ltU83NA.jpg)

I wasn't able to reproduce this behaviour, but I noticed that the upload starts with two concurrent file uploads but sometimes there can be three concurrent uploads.

**Comment by poetwang** [comment]
fixed in 1.9.8
