### ISSUE TITLE
Use actual device name for identification

### ISSUE THREAD

**Issue by thewilli** [haiwen/seafile-iOS#58]
The iOS App registeres each device as *iphoneos*, which is not very useful if you e.g. use an iPhone as well as an iPad.

It would be better to use the [actual name](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIDevice_Class/index.html#//apple_ref/occ/instp/UIDevice/name) of the device. As there is an additional *platform* parameter which is already filled with *ios*, writing the platform name in the name seems pretty useless.

The change need to be done [here](https://github.com/haiwen/seafile-iOS/blob/4681456563b3220f67554b0dc9aadf3b60b76530/common/SeafConnection.m#L375).

**Comment by poetwang** [comment]
sounds good

**Comment by thewilli** [comment]
Issue is closed with 4a9a5ad
