### ISSUE TITLE
Cannot log out, remove, or change password in linked accounts

### ISSUE THREAD

**Issue by yakaneli** [haiwen/seafile-iOS#61]
I'm on the 5S. I change my password on my private server, but looks like there is no way to update the account in the iOS client without deleting all the app data. Looks like there is no way to:

- edit accounts (like user name or password)
- delete accounts

**Comment by poetwang** [comment]
You can long press the account , it will pop up a menu, in which you can edit or remove account.

**Comment by yakaneli** [comment]
Ahh thanks. It's not terribly intuitive to figure that out, but I'm glad the functionality is there!
