### ISSUE TITLE
Cannot upload files to server using SNI

### ISSUE THREAD

**Issue by mterhar** [haiwen/seafile-iOS#62]
Running multiple HTTPS sites on the same server became possible with the implementation of SNI in most browsers.  The OS X client and web interfaces worked fine with the services running on an SNI box. The iOS client would connect and get the library information but then crashed or stalled whenever a file upload was attempted.

Upon disabling SNI and restarting services, the iOS client upload started working.

**Comment by confile** [comment]
What is SNI?

**Comment by mterhar** [comment]
It is the TLS extension that allows multiple HTTPS sites to be hosted on the same IP address.  All contemporary browsers support it. 

https://tools.ietf.org/html/rfc3546#section-3.1

**Comment by poetwang** [comment]
does the download work?

**Comment by poetwang** [comment]
Do you use a self-signed cert?

**Comment by mxbode** [comment]
Same problem here! Multiple SSL- vhosts with SNI works well for the linux client. But the windows client seems to be broken.
