### ISSUE TITLE
Automatically generate thumbnails of images without having to download them first

### ISSUE THREAD

**Issue by thewilli** [haiwen/seafile-iOS#64]
As far as I understand Seafile 4.1.0 [introduced an API](https://seacloud.cc/group/3/wiki/server-changelog/) that allows thumbnail generation.

This API should be used to display (download) thumbnails for all photos - not only for those pictures that were already downloaded. If you are browsing a huge photo collection and are looking for a certain picture, it is currently very annoying and time-consuming to cherry-pick images until you've reached what you were looking for.

**Comment by poetwang** [comment]
will be added to the next version

**Comment by poetwang** [comment]
Fixed in v1.9.9

**Comment by thewilli** [comment]
@poetwang when will v1.9.9 be submitted to the iOS app store?
