### ISSUE TITLE
[feature request] Import multiple photos to Photos app

### ISSUE THREAD

**Issue by Alcatr4zz** [haiwen/seafile-iOS#65]
Currently, importing photos to the Photos app is only possible with one photo at a time. This is very annoying when you want to import a lot of photos or even a whole folder.

So, it would be great to have the ability to select all the desired photos and import them all at once.

**Comment by yakaneli** [comment]
This is related, I actually store my music on seafile and then like to open it with VLC. It would be great if I could do this with multiple files or even better folders at once.

**Comment by confile** [comment]
+1

**Comment by confile** [comment]
I suggest integrating the following photo browser into seafile ios: 

https://github.com/mwaterfall/MWPhotoBrowser

**Comment by steffimueller** [comment]
+1 I hope that too. Photo browsing is very annoying with only one photo at the time.

**Comment by MartinBusch** [comment]
+1 @poetwang I saw in another thread that this feature is planed. I think it would be very healpful because watching photos might be the number one reason to use seafile.

**Comment by poetwang** [comment]
Now you can  import  all images in the same folder at once.

**Comment by confile** [comment]
@poetwang What about the photo browser? https://github.com/mwaterfall/MWPhotoBrowser
