### ISSUE TITLE
Camera Upload: strips EXIF data and other problems

### ISSUE THREAD

**Issue by jan616** [haiwen/seafile-iOS#67]
Resolution and orientation are now correct with V1.9.8, but now we have the following problems with the Camera Upload:
* EXIF data is stripped
* file date of uploaded image file is current date, not shot date
* resolution and quality are OK now, but file size is BIGGER than original iPhone image file (factor two or three!)

Seafile iOS app V1.9.8 on iPhone 4S with iOS 8.3

**Comment by jan616** [comment]
This bug is still present in v2.0.0 (iPhone 4S with iOS 8.4).

**Comment by bovi** [comment]
Still present in v2.1.0 (iPhone 6 with iOS 8.4) and a really killer for the auto upload function.

**Comment by poetwang** [comment]
fixed in v2.1.1

**Comment by jan616** [comment]
It's working now. Thanks!

**Comment by bovi** [comment]
Works here too. Thanks @poetwang! that was the last part I used still iCloud for. Thanks so much for this great tool!
