### ISSUE TITLE
iPhone 5 / Syncing 3000+ Pictures

### ISSUE THREAD

**Issue by Moep90** [haiwen/seafile-iOS#69]
Iphone 5 / 16G
IOS 8.3 (Upgrade today morning after doom)

I tried yesterday the ios app of seafile. 
I started autosync for camera pictures which are 3000+ pics in 3-4 GB. 
I had about 1.1 GB free space left. My storage went full after ~ 1.1 GB upload to the seafile server by filling the local cache, too. 
I deleted the local cache several times to upload more images. But today morning a got the doom. My iPhone went full 0bytes left. Seafile shows up with just usual app install size. The space is just gone. And even after I uninstalled Seafile I dont have any space.

**Comment by poetwang** [comment]
Seafile may use much cache space while uploading photos, but after wipe cache, the space should be freed. After Seafile uninstalled, all the space will be freed by the iOS. So i think you should make sure that whether these space are occupied by some other apps.

**Comment by poetwang** [comment]
In the next version, seafile will release the space after photos are uploaded.

**Comment by Moep90** [comment]
that may be. But it wouldnt operate till at least I dont know 100 MB are free. And if i have less space than the photos are big than every seafile user has a problem on ios. Everthing stops working properly seafile client crashs so that the cache finally isnt wiped because the upload process isnt finished. 

I can gurantee you that ive done nothing with other apps at the same time. So it must be a problem with seafile client on ios. 

Maybe xou can wipe the cache if it is 50MB or so to make sure an iphone is still operational.

cheers Danny

**Comment by poetwang** [comment]
Sure, the cache will be wiped after a photo is uploaded
