### ISSUE TITLE
Directly delete image from preview screen

### ISSUE THREAD

**Issue by thewilli** [haiwen/seafile-iOS#70]
If I tap on an image, it is displayed in a preview screen, where I can swipe to the next and previous image, star it, share it or open it in another app.

I would like to use my iOS device to quickly go through some uploaded pictures and delete all unwanted ones. Could you please consider adding a "delete" button at the top, next to the three existing ones?

**Comment by poetwang** [comment]
Sounds good, will be added.

**Comment by poetwang** [comment]
fixed in v2.0.0
