### ISSUE TITLE
iOS App 1.9.9 Does not connect to server on https with self signed certificate

### ISSUE THREAD

**Issue by confile** [haiwen/seafile-iOS#71]
When I connect to my private server with http it works fine but connecting with https does not work. It shows connecting but never did.

<img width="330" alt="foto_11_07_15_12_17_02_png_bei_51___form_1_kopie__blau_8___" src="https://cloud.githubusercontent.com/assets/64265/8633416/d36718c2-27c7-11e5-9ed1-faea1bce2789.png">

**Comment by thewilli** [comment]
@confile do you use a self-signed certificate? Can you access your server's web interface using Safari on your iOS device (without any warning or error message)?

**Comment by confile** [comment]
Yes I use a self signed certificate. Yes I can access my servers web interface from Safari  I can also access it from my Mac.

**Comment by thewilli** [comment]
@confile a common misunderstanding is that apps can use (trust) certificates that are installed on the device. So if you installed a certificate on your iPhone, Safari won't show an error, but every non-Apple app still won't trust the connection to your server. Unfortunately there is nothing an app developer can do.

I ran over the source code and think there is a way for you to bypass this limitation: The app [tries to load](https://github.com/haiwen/seafile-iOS/blob/master/common/SeafConnection.m#L128) a certificate for the Seafile host from the documents folder of the app. So - in theory - you could place a file myhostname.cer into a *certs* subfolder of the app's documents folder (by using iTunes). 

@poetwang am I right?

**Comment by confile** [comment]
Isn't that a very complicated solution?

**Comment by thewilli** [comment]
the alternative would be to allow the user to skip the chain-of-trust verification, or to accept any certificate. Both is very undesirable. I would recommend you to get an ordinary certificate. There a few provider where you can get certificates for free.

**Comment by poetwang** [comment]
While seafile try to login a server,  it will check the certificate, if it is a self-signed certificate(untrusted certificate),  it will ask the user whether it should continue with this untrusted certificate. If user choose to continue, then it will save the cert into a certs subfolder of the app's documents folder and put the cert into the whitelist of this account.  Then when the app access this account's files in seafilePro, the saved cert is used.

So the app is supposed to know that the server is using a self-signed certificate and popup a dialog, ask user whether it should continue, or cancel. 

Is there any other messages when it failed to login?

**Comment by confile** [comment]
There is no other fail message. So it means I should first login with mobile Safari in the browser on the cell phone I an using the Seafile App with. And after using mobile safari I should use the App on the same device to get the correct cetificate save. Is this correct?

**Comment by confile** [comment]
I tried this but it did not work. Seafile iOS App does not connect to private server with self signed certificate.

**Comment by poetwang** [comment]
No, login with mobile Safari in the browser won't work. You can try to turn on "Allow invalid certificates" in the Settings/SeafilePro.

**Comment by confile** [comment]
The iOS app does not have "allow invalid certificate" ??

**Comment by poetwang** [comment]
![img_0294](https://cloud.githubusercontent.com/assets/1908737/8641231/c11b6cfe-2943-11e5-9185-fb2648dd29aa.PNG)

**Comment by confile** [comment]
I did this but then I see the following screen while trying to login: 

![foto_13_07_15_18_25_38_png_bei_100___form_3__rgb_8___](https://cloud.githubusercontent.com/assets/64265/8654768/c603b156-298c-11e5-8c49-4adeb5606964.png)

**Comment by MartinBusch** [comment]
+1 same problem here for v. 2.0.0

**Comment by poetwang** [comment]
will be fixed in next version

**Comment by confile** [comment]
@poetwang When will you release the next version?

**Comment by poetwang** [comment]
The next version will be submitted to app store tomorrow

**Comment by confile** [comment]
Great I look forward to test it.

**Comment by hutzla** [comment]
Pro Server in v4.4.1 (ubuntu 14.04)
iPad app v 2.1.2
self signed ssl certificate

I still have this problem: App should allow untrusted certificates, but I can't connect to the server. 
iPhone App works, web interface works. Seems to be a bug in current iPad app.

**Comment by poetwang** [comment]
what is the version of iOS on your iPad?

**Comment by confile** [comment]
My iPad is 8.1

**Comment by poetwang** [comment]
Actually, the app for iPhone and iPad is the same. So it is really wired that iPhone App works and iPad does not work. Try to remove Seafile app and reinstall it on iPad.

**Comment by onlinetocode** [comment]
Same here regarding untrusted certificates. It works if the button for "allow invalid certificates" is unchecked.

Open Source Server v6.0.8 (ubuntu 16.04)
iPhone App v2.5.6
self signed ssl certificate

**Comment by Lisheng2016** [comment]
same problem on centos7, uncheck the "Allow invalid certifications" and the prompt poped out, everything is working again.
