### ISSUE TITLE
support automatically uploading of images in the background

### ISSUE THREAD

**Issue by thewilli** [haiwen/seafile-iOS#74]
Currently images are only uploaded while the Seafile app is opened.

I know there are several iOS limitations about running in the background, but they can be bypassed e.g. by geofencing (start uploading in the background when you arrive at home, work, university ...). The [PhotoSync](http://photosync-app.com) app is a good example how this can be achieved.

The Seafile iOS app should support this.

**Comment by poetwang** [comment]
Because of Apple limitations,  app is only allowed to upload for a short time after you quit the app. The way that Dropbox gets around this is to use Location Services.  Seafile will try to use this way too.

**Comment by poetwang** [comment]
done
