### ISSUE TITLE
Foto Upload does not start with https

### ISSUE THREAD

**Issue by confile** [haiwen/seafile-iOS#77]
Version: 1.9.9
iPhone 5 iOS 7.1.1.

I tried to upload photos my seafile private server. The library is connected with https and a valid certificate. 

As you can see from the following image. The upload does not start: 

![image](https://cloud.githubusercontent.com/assets/64265/8721465/ee7cbd0a-2bba-11e5-9ac7-4a1b6741caec.png)

**Comment by confile** [comment]
The library is not encrypted.

**Comment by steffimueller** [comment]
+1 I have the same problem. It also does not with with http.

**Comment by poetwang** [comment]
Does the download work?

**Comment by confile** [comment]
The download works

**Comment by confile** [comment]
@poetwang Upload never starts even when I'm am in the same network.

**Comment by confile** [comment]
No I was wrong with https even download does not work.

**Comment by poetwang** [comment]
Does it work on web browser, download and upload?

**Comment by confile** [comment]
Using Seafile RaspberryPi version 4.3.0. I tried on the browser when I do upload I get: 

![bibliotheken_-_private_seafile](https://cloud.githubusercontent.com/assets/64265/8893558/ece4fd7c-3394-11e5-8278-f81eff9efec8.png)

When I try to download I get: 

![private_seafile](https://cloud.githubusercontent.com/assets/64265/8893560/21d58600-3395-11e5-8447-fe65535094db.png)

In summary upload und download does not work on the browser. 

Upload and download only work on the Desktop Seafile client for me.

**Comment by freeplant** [comment]
You don't correctly set SERVICE_URL in ccnet.conf and FILE_SERVER_ROOT in seahub_settings.py

**Comment by confile** [comment]
How do I find the correct values for these variables? @freeplant

**Comment by confile** [comment]
I am using NGINX as a proxy. Here is my NGINX config for seahub:

```
server {
    listen 8001; # <--------------------------------------- NGINX PORT
    ssl on; # <-------------------------------------------- SSL

     ssl_certificate /etc/nginx/ssl/ssl-michaelgorski-org-unified.crt; # <--------- SSL
     ssl_certificate_key /etc/nginx/ssl/ssl-michaelgorski-org.key; # <----- SSL
     server_name home.myserver.de; # <----------------- CHANGE THIS

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    server_tokens off;

    error_page 497  https://$host:$server_port$request_uri;

    location / {
        fastcgi_pass    127.0.0.1:8000;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;

        fastcgi_param   SERVER_PROTOCOL $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
        fastcgi_param   HTTPS   on;
        fastcgi_param HTTP_SCHEME https;

        access_log      /var/log/nginx/seahub.access.log;
        error_log       /var/log/nginx/seahub.error.log;
    }
    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8082;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
    }

    location /media {
        root /home/seafile/seafile/seafile-server-latest/seahub; 
    }
}
``` 

Here is my ``ccnet.conf ``:

```
[General]
USER_NAME = home
ID = 123123213123123123263e99092610b5222bc7c0d77ac8
NAME = home
SERVICE_URL = https://myserver:8001

[Network]
PORT = 10001

[Client]
PORT = 13418
```
Here is my ``seahub_settings.py``: 

```
SECRET_KEY = "123456789123456789"
HTTP_SERVER_ROOT = 'https://myserver:8001'
```

Is there anything missing?

**Comment by confile** [comment]
I corrected my FILE_SERVER_ROOT and set the correct SERVICE_URL: 
```
FILE_SERVER_ROOT = 'https://www.myserver:8001'
```
and
```
FILE_SERVER_ROOT = 'https://www.myserver:8001/seafhttp'
```

Now upload and download works with the browser interface. But upload does not work with the ios app. Download on iOS works partially. Only the preview images are downloaded directly. When you tap on a preview to see this: 

![foto 26 07 15 20 34 52](https://cloud.githubusercontent.com/assets/64265/8895310/dd35c83e-33d5-11e5-948a-b6afc8b3f74b.png)

Again upload does not work.

**Comment by poetwang** [comment]
can not reproduce, skip
