### ISSUE TITLE
Camera Upload: I can't chose Upload Destination

### ISSUE THREAD

**Issue by mjut** [haiwen/seafile-iOS#78]
I am dealing with a annoying behavior in the settings:
It is not possible to tap and choose the "Upload Destination" for the automatic Camera Upload. (its all enabled)

**Comment by ldumont** [comment]
Same problem here, I removed the app and installed it again but it didn't correct the problem.

Iphone 6 IOS 8.4
Seafile 1.9.9

**Comment by mjut** [comment]
@ldumont okay. I got it working too: WITHOUT choosing the destination. My images are loading to the folder "Camera Uploads" now. I am not sure, how I fixed it. ;)

Now, I am dealing with up to 3,000 images and videos in this folder. Browsing the folder contents can be very frustrating. Sorting the content "last uploaded on top of the list" would com ein handy...

**Comment by steffimueller** [comment]
+1 I have the same problem cannot fix the destination.

**Comment by steffimueller** [comment]
Sorry I mean I cannot choose a destination.

**Comment by poetwang** [comment]
fixed in v2.0.0
