### ISSUE TITLE
Waiting for upload...

### ISSUE THREAD

**Issue by dseichter** [haiwen/seafile-iOS#8]
Using the seafilePro App 1.0 on my iPad2 and iPhone5. 
Everything works fine but I can't upload any file.
If I add a photo, an attachment, whatever, the file is listed inside the choosen library, but the status is "Waiting for upload..."

I restartet everything, App, iPhone/iPad, re-added the account, restarted the server, but nothing. The status is still the same "Waiting for upload...".

**Comment by jsongo** [comment]
Unfortunately the same problem too, while sometimes it works fine but sometimes doesn't. It may be an occasionally-happened problem that your team should take serious of.

**Comment by scottcc** [comment]
Hey @jsongo, @ghost's comment is from 2014, and this ticket is closed. You should probably open a new ticket and link against this rather than commenting 4 years after the fact. That's just a suggestion I have, I'm not affiliated with haiwen in any way (just an avid user of the software). Cheers!
