### ISSUE TITLE
Photos are not always loaded properly

### ISSUE THREAD

**Issue by thewilli** [haiwen/seafile-iOS#83]
This behavior is irritating, especially for unexperienced user. It can be reproduces on the current v2.0.0 and earlier versions as follows:

1. Ensure the app is not started, not even in the background (kill it)
2. Open the app, and open a library with images in it
3. Touch an image that is **not cached**

**Expected Behavior:** 
The image is loaded (loading indicator) and displayed afterwards

**Actual Behaviour:**
Neither is a loading indicator shown, nor the image (no matter how long you wait). If you go back to the library view, and reopen the same (or any other image), the problem does not occur again. It's only for the first image.

**Comment by thewilli** [comment]
this is how the apps looks like after step 3.

![screenshot](https://cloud.githubusercontent.com/assets/1206639/9106752/d0e71b00-3c22-11e5-8f8e-0790aee64800.png)

**Comment by MartinBusch** [comment]
+1 same problem here

**Comment by poetwang** [comment]
it is a bug, will be fixed in the next version.
