### ISSUE TITLE
V 2.1.0 iOS7 Upload does not start

### ISSUE THREAD

**Issue by confile** [haiwen/seafile-iOS#84]
Even after the latest update the upload does not start up iOS7 to private server on https. It works only with ios8.

**Comment by poetwang** [comment]
Can you provide more details about some problem, i can not reproduce it, which device(iOS7) do you used?

**Comment by confile** [comment]
iOS 7.1.2 I think you can skip this because ios 7 is down to 15%.

**Comment by poetwang** [comment]
Can not reproduce, i will skip this.
