### ISSUE TITLE
2.1.0 dowload of images is very slow and does not show all images.

### ISSUE THREAD

**Issue by MartinBusch** [haiwen/seafile-iOS#85]
If you browse a list of photos it takes so long until the photos are loaded. Sometimes an error is show as you can see in the picture: 

![foto 15 08 15 12 33 27](https://cloud.githubusercontent.com/assets/13513241/9288512/049b024e-434a-11e5-9dc4-8e087c3f7971.png)

**Comment by steffimueller** [comment]
+1 I have the same problem

**Comment by poetwang** [comment]
maybe the network is bad. what about downloading other files?
