### ISSUE TITLE
No copy and paste in editor

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile-iOS#88]
When editing files (e.g. markdown files) you can't use the copy and paste features of iOS.

**Comment by poetwang** [comment]
You can tap the text softly, then select the words you want to copy

**Comment by dakira** [comment]
This works as expected, when viewing the file, but not when editing.

When editing:

1. touch and hold
2. magnifier appears to make positioning the cursor easier
3. release

Nothing happens.

When I tap around multiple times, I sometimes get the selection dialog. But that is not expected behavior and not easily reproducable. Especially pasting text becomes nearly impossible since you can't position the cursor using touch-and-hold.

**Comment by poetwang** [comment]
fixed
