### ISSUE TITLE
Account password is remembered in account settings

### ISSUE THREAD

**Issue by m-andre** [haiwen/seafile-iOS#89]
While playing around with regards to issue #87 I noticed that account password is remembered in account settings - so in case I unlink the iOS client using Seafile web interface, I can immediately login again without having to enter the password.

Would it be possible to change it in a way that account password is not remembered and after unlinking library I have to enter it again?

Thanks.

**Comment by poetwang** [comment]
Sounds good.

**Comment by poetwang** [comment]
fixed
