### ISSUE TITLE
Bigger Preview Image

### ISSUE THREAD

**Issue by confile** [haiwen/seafile-iOS#90]
Could you please provide bigger preview images.

**Comment by poetwang** [comment]
what do you mean "bigger"? full screen?

**Comment by confile** [comment]
I mean like in this lib: https://github.com/mwaterfall/MWPhotoBrowser

It would be really amazing if you could integrate this lib into seafile.

**Comment by confile** [comment]
I mean seafile ios app.

**Comment by poetwang** [comment]
yes, i know. I use some code of MWPhotoBrowser in seafile ios app,  I mean do you want full screen  preview images?

**Comment by confile** [comment]
Yes full screen preview Images would be great.

**Comment by confile** [comment]
Right now seafile ios is not very useful for image browsing. Image browsing is the best when you browse like this: 

![mwaterfall_mwphotobrowser](https://cloud.githubusercontent.com/assets/64265/11317386/980d975a-902d-11e5-8ef6-92b7e45f5aec.jpg)

**Comment by confile** [comment]
@poetwang is this feature now implemented?

**Comment by poetwang** [comment]
yes, you can open photo browser in the edit menu
