### ISSUE TITLE
Crash app when cancel editing text or md

### ISSUE THREAD

**Issue by 34x** [haiwen/seafile-iOS#91]
How to reproduce (in last version, iTunes and github):

Open *.txt or *.md file, tap edit, then tap cancel. 

The app will crash in any cases (on simulator 9.0 and 5s with 9.0.2)

As I found it happen in the EgoTextView.m on the 412 line, and the solution is just check delegate for null, but I am not sure that is a good way to fix it but still not found other way to fix it. Maybe someone else can solve it in a more proper way.

    - (void)setDelegate:(id<EGOTextViewDelegate>)aDelegate {
        // my solution
        if (!aDelegate) {
            return;
        }
        // end of solution
        [super setDelegate:(id<UIScrollViewDelegate>)aDelegate];

**Comment by poetwang** [comment]
I will try to find a better way to fix this. thx

**Comment by kmnns** [comment]
Can confirm this crash also for saving. It is kind of a killer feature for me, because it would be a perfect substitute for both iOS Notes and Owncloud Notes.

**Comment by poetwang** [comment]
fixed
