### ISSUE TITLE
Crash when uploading many files and scrolling

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile-iOS#92]
When uploading around 20 pictures and scrolling through the list of files being uploaded, the client crashes sometimes. Might be an out-of-memory problem. When no other apps are open, this crash doesn't happen.

**Comment by poetwang** [comment]
seafile might use too much memory when uploading photos, i will try to optimize memory usage.

**Comment by hoba87** [comment]
The problem is not limited to uploading photos only, crashes also happens when viewing (big) photos.

**Comment by dakira** [comment]
So basically, out-of-memory is not handled gracefully.

**Comment by poetwang** [comment]
fixed
