### ISSUE TITLE
Low resolution full screen (pre-)view

### ISSUE THREAD

**Issue by hoba87** [haiwen/seafile-iOS#93]
Hi,

for photos there should be the possibility to load them with adjusted resolution that fits to the resolution of the device as default. E.g. on my iPhone or iPad I do not need the full resolution of a DSLR camera to view them, which is probably the most used way for photos in mobile apps.
That would massively speed up the download time, which is especially critical for home servers.
Of course, the option to download the full resolution file should still be possible.

**Comment by poetwang** [comment]
This will make the app too complex.
