### ISSUE TITLE
Uploading big files doesn't work

### ISSUE THREAD

**Issue by hoba87** [haiwen/seafile-iOS#96]
When I try to upload big files (movies), this doesn't work. With using a web browser no problem appears, so it seems the bug is related to the iOS app.
While uploading a file of 95MB works, 392MB seems to be too much. The app seems to be in a loop trying to upload the file again and again.

**Comment by poetwang** [comment]
I will try to optimize big file upload soon.

**Comment by poetwang** [comment]
fixed in v2.4.7
