### ISSUE TITLE
Unable to choose destination and enable automatic upload

### ISSUE THREAD

**Issue by narolinus** [haiwen/seafile-iOS#97]
If I try to enable automatic upload it's always disabled again when closing settings. Additionally I am unable to choose a destination. Tapping the setting does not show any reaction.

None of the older workarounds, like tapping on "only wlan", work.

Sefile Server: 5.0.1 
Seafile Client 2.1.2
iOS 9.1

**Comment by poetwang** [comment]
You should enable auto upload first.

**Comment by poetwang** [comment]
Which device do you use, iPhone? iPad?

**Comment by narolinus** [comment]
iPad Air

**Comment by narolinus** [comment]
Nevermind. This seems to be a problem with this specific iPad. On another one (restored from the same backup) it works as expected. Very strange.
