### ISSUE TITLE
Auto-upload doesn't refresh edited photos

### ISSUE THREAD

**Issue by yakaneli** [haiwen/seafile-iOS#98]
I'm not totally sure what the correct functionality should be here, but if you edit a photo in your camera roll, the uploaded version on seafile does not update to the new version. Shouldn't it? I would imagine if you edited a photo prior to the initial upload, it would upload the edited version.

**Comment by poetwang** [comment]
Now the app did not monitor the modification of the uploaded photos, so if you edit the photo, the edited version will not be uploaded. Maybe in the next version this function will be supported
