### ISSUE TITLE
Internal seafile links - Feature request

### ISSUE THREAD

**Issue by GITchristoph** [haiwen/seafile-iOS#99]
Hi Poet

Back then we have recommended to integrate internal share links for the seafile desktop client.
They work great and we use them a lot.

https://github.com/haiwen/seafile/issues/1059

I already asked at some stage if it would be possible to integrate this into the iOS seafile client as well.
Because that would be just uber-cool to be able to send internal links in iMessage or Slack or Trello and then all seafile users can open the file directly within the seafile app.
No need anymore to also email them

Even confidential content can be sent like this, because only persons with the right seafile permissions can access the link.

I think this would be a very unique selling point for seafile.

So my question is: Would you consider implementing that option into the iOS app?

Greetings, Chris

**Comment by poetwang** [comment]
Got it, I will take this into consideration.

**Comment by poetwang** [comment]
Added  in v2.1.5

**Comment by GITchristoph** [comment]
this is absolutely great. 
Thanks so much for taking the time. 

I hope I / we are not the only ones enjoying and using it. 

Chris
